maddevsio/maddevs

src/assets/styles/_content-home.scss
src/assets/styles/_media-home.scss
src/components/Home/Services.vue
src/locales/en/resource.json
src/locales/ru/resource.json

1. Changed indent on mob screen
2. Changed title on section Services

Develop to Master

---

.nuxt/client.js
.nuxt/index.js
.nuxt/utils.js
components/Home/BestPractices.vue
components/Home/QuickProjectStart.vue
components/Home/Services.vue
nuxt.config.js
package.json
plugins/google-analytics.js
plugins/yandex-metrics.js

MND-269 optimized methods in BestPractices component
MND-269 changed methods in QuickProjectStart component
MND-269 changed methods in Services component
MND-269 added yandex-metrics
MND-269 added google-analytics plugin
MND-269 connected plugin google-analytics

MND-269 to develop

---

assets/styles/_global.scss
assets/styles/_vars.scss
components/Services/ItConsultingContent.vue
components/Services/ItOutsourcing.vue
components/Services/ItСonsulting.vue
components/Services/OutsourcingContent.vue
components/Services/SoftwareDevelopment.vue
components/ui/button-trigger.vue
pages/_lang/services.vue

1. Added mark up and styles for it consulting section
2. Changed global styles 
3. Added new media styles for button component and other sections

MND-550 added mark up and styles for it consulting section

---

components/About/TechnologiesItem.vue
components/Banner.vue
components/ui/navigation-list.vue
tests/__snapshots__/banner.spec.js.snap
tests/banner.spec.js

1. Fix rendering logic in Banner component 
2. Removed unuse code

MND-653 improve v-if condition in banner

---

assets/styles/_vars.scss
components/About/WhyUs.vue
pages/_lang/index.vue
tests/__snapshots__/whyUs.spec.js.snap
tests/whyUs.spec.js

1. Added html markup and styles
2. Added media styles 
3. Added important tests for new component

MND-510 added markup for Why Us? section

---

.nuxt/App.js
.nuxt/client.js
.nuxt/components/nuxt-child.js
.nuxt/components/nuxt-error.vue
.nuxt/components/nuxt-loading.vue
.nuxt/index.js
.nuxt/router.js
.nuxt/server.js
.nuxt/store.js
.nuxt/utils.js
components/About/CustomerTestimonials.vue
components/About/QuickProjectStart.vue

Added a call to the init function when the widget is re-mounted to the DOM tree

MND-499 fixed init clutch widget

---

components/About/CaseStudies.vue
components/About/SingleProject.vue
tests/__snapshots__/caseStudies.spec.js.snap
tests/singleProject.spec.js

- Improve and refactor CSS layout for small screens

MND-498-IMPROVE Refactored Case Studies' layout for small screens

---

components/About/CaseStudies.vue
components/About/ContributionWidget.vue
components/About/SingleProject.vue
tests/__snapshots__/caseStudies.spec.js.snap
tests/__snapshots__/contributionWidget.spec.js.snap
tests/__snapshots__/singleProject.spec.js.snap
tests/caseStudies.spec.js
tests/contributionWidget.spec.js
tests/singleProject.spec.js

- Add new layout for case studies' mobile screens according to the new design
- Add new logic for Widget component 
- Add unit tests

MND-693 Add new layout for case studies' mobile screens

---

assets/styles/_global.scss
assets/styles/_vars.scss
components/About/InfrastructureTechnologiesItem.vue
components/About/QuickProjectStart.vue
components/About/TechnologiesAndTools.vue
components/About/WhyUs.vue
components/Footer/footer-form.vue
components/IconsGroup/InfrastructureFirstIconsGroup.vue
components/IconsGroup/ProjectManagement.vue
components/ui/contact-me-modal.vue
components/ui/form-checkboxes.vue
components/ui/mobile-menu.vue
plugins/vee-validate.js
tests/__snapshots__/header.spec.js.snap

1. Added media styles for modal window
2. Fixed markup bugs
3. Refactored part of styles
4. Added classes logic for inputs

MND-617 added media styles for modal window 

---

components/About/MeetOurExperts.vue
components/About/MeetOurExpertsMobile.vue
tests/__snapshots__/meetOurExperts.spec.js.snap
tests/__snapshots__/meetOurExpertsMobile.spec.js.snap
tests/meetOurExpertsMobile.spec.js

1. Added mobile slider for Our experts section

MND-517 added mobile slider for Our experts section

---

components/Careers/CareersForm.vue
components/Careers/FileInput.vue
components/Careers/RadioButton.vue
tests/__snapshots__/careersForm.spec.js.snap
tests/__snapshots__/fileInput.spec.js.snap
tests/__snapshots__/radioButton.spec.js.snap
tests/careersForm.spec.js
tests/fileInput.spec.js
tests/radioButton.spec.js

- Add main test cases to careersForm
- Add tests for FileInput component
- Add tests for RadioButton component

MND-684 Add tests for Careers page's components

---

components/Careers/CareersForm.vue
components/Careers/FileInput.vue
components/Careers/RadioButton.vue

- Add emit an event to RadioButton component
- Fix radio elements class name
- Add RadioButton component, remove unused classes from CareersForm
- Add styles to FileInput component and remove unused classes from CareersForm
- Add FileInput component
- Fix linter's error

MND-708 Add reusable components to Careers' page

---

assets/styles/_vars.scss
components/Careers/Button.vue
components/Careers/CareersForm.vue
tests/__snapshots__/button.spec.js.snap
tests/__snapshots__/careersForm.spec.js.snap
tests/button.spec.js

- Add reusable Button component, add global style variables
- Add media queries to Button component
- Add tests for Button component
- Add global style constants

MND-690 Add Button component in Careers page and it's tests

---

components/About/WeCreateItProjectFor.vue
components/ui/get-case-studies-modal.vue
layouts/default.vue
tests/__snapshots__/getCaseStudiesModal.spec.js.snap
tests/getCaseStudiesModal.spec.js

1. Added new modal widnow for button get case studies

MND-715 added new modal widnow for button get case studies

---

components/About/CaseStudies.vue
components/About/SingleProject.vue
tests/__snapshots__/caseStudies.spec.js.snap
tests/__snapshots__/singleProject.spec.js.snap

- fix single projects background images for large screens
- add styles for each Case Studies item

MND-752 Add links to Case Studies' page and fix styles

---

components/Projects/OpenSource.vue
tests/__snapshots__/openSource.spec.js.snap

- Add Mad Dev's GitHub link to Github's icon

MND-757 Add link to github's icon

---

assets/img/Footer/messenger.svg
components/Footer.vue
components/Footer/footer-contacts.vue
tests/__snapshots__/header.spec.js.snap

MND-760 Add messenger'a icon and link in the footer

---

components/Careers/CareersForm.vue
tests/careersForm.spec.js

- Add carets styles
- Add autofocus on name input in Career's form
- Add unit tests

MND-759 Added styles to the caret and logic for autofocus in Career's form.

---

components/Careers/CareersForm.vue
tests/careersForm.spec.js

- Fix placeholders rendering for inputs and add its styles
- Add validation for radio buttons in Career's form and change … handling and submission of form's data
- Delete unused package imports

MND-758 Fix placeholders rendering, add validation to radio buttons and change form submission logic

---

components/Projects/Customer.vue
components/Projects/Customers.vue

- Fix Valued Customers section's header
- Fix logo's font style
- Fix responsivity of Valued Customers section

MND-773 Fix responsive layout of Valued Customers section

---

components/About/ContributionWidget.vue
components/About/SingleProject.vue
components/Banner.vue
components/Careers/CareersForm.vue
components/Careers/RadioButton.vue
components/Projects/Customers.vue
tests/__snapshots__/caseStudies.spec.js.snap
tests/__snapshots__/contributionWidget.spec.js.snap
tests/__snapshots__/singleProject.spec.js.snap

- Fix paddings in Case Studies and Valued Customers
- Fix the radio button's position in the Careers' form
- Fix error message's layout for small screens
- Fix tests and linter errors
- Fix Careers form's header section

MND-804 Fix media queries for Careers and Projects pages 

---

assets/styles/_global.scss
components/About/InfrastructureTechnologiesItem.vue
components/About/TechnologiesAndTools.vue
components/About/TechnologiesItem.vue
components/IconsGroup/BackendIcons.vue
components/IconsGroup/FrontendIcons.vue
components/IconsGroup/InfrastructureSecondIconsGroup.vue
components/IconsGroup/MobileIcons.vue
components/IconsGroup/ProjectManagement.vue

1. added styles for Technologies & Tools section

MND-781 added styles for Technologies & Tools section

---

assets/styles/_global.scss
components/About/CaseStudies.vue
components/Projects/Customers.vue
components/Services/InfrastructureContent.vue
components/Services/InfrastructureOptimisation.vue
components/Services/ItConsultingContent.vue
components/Services/ItOutsourcing.vue
components/Services/ItСonsulting.vue
components/Services/OutsourcingContent.vue
components/Services/SoftwareDevelopContent.vue

- Fix Services layout of 1440px
- Fix Services page's layout for 1280px
- Fix background flames top positioning in projects page
- Add line-height for main-title in global variables

MND-728-IMPROVE Fixed Services page's layout for 1280px and 1440px

---

components/About/CaseStudies.vue
components/About/SingleProject.vue
tests/__snapshots__/caseStudies.spec.js.snap
tests/__snapshots__/singleProject.spec.js.snap
tests/caseStudies.spec.js
tests/singleProject.spec.js

Add Medium links to Case Study's items

MND-816 Add Medium links to Case Study section's items

---

components/Footer/footer-contacts.vue
components/Header.vue
tests/__snapshots__/header.spec.js.snap

1. Change phone numbers in header and footer
2. Fixed styles for phones sections

MND-807 added minor fixes in markup

---

components/About/CaseStudies.vue
components/Banner.vue
components/Careers/CareersForm.vue

- Fix Project's title
- Add media query for Project's background image
- Fix linter errors

MND-817 Fix Project page's title

---

.nuxt/index.js
.nuxt/router.js
components/Banner.vue
components/Careers/CareersForm.vue
components/ui/navigation-list.vue
containers/ModalContainer.vue

1. Added new styles for services banner
2. Fixed layout bugs

MND-807 added new styles for services banner

---

components/Services/InfrastructureContent.vue
components/Services/InfrastructureOptimisation.vue
components/Services/ItConsultingContent.vue
components/Services/ItOutsourcing.vue
components/Services/ItСonsulting.vue
components/Services/OutsourcingContent.vue
components/Services/SoftwareDevelopContent.vue
components/Services/SoftwareDevelopment.vue

- Add media queries for ItOutsourcing and Software development
- Add media queries for icon-list in the Services page
of 768px
- Add media queries for IT Consulting section of 768px

MND-814 Added media queries for Services page's 768px width

---

components/About/CustomerTestimonialMobileSlider.vue
components/About/CustomerTestimonials.vue

1. Adapted section by new design

MND-783 added new styles for customer testimonials section

---

components/Services/InfrastructureContent.vue
components/Services/InfrastructureOptimisation.vue
components/Services/ItConsultingContent.vue
components/Services/ItOutsourcing.vue
components/Services/OutsourcingContent.vue
components/Services/SoftwareDevelopContent.vue

- Add media queries for IT Outsourcing and Software Develop sections of 376px width
- MND-815 Add media queries for InfrastructureOptimisation and ItConsulting sections of 375px

MND-815 Add media queries for Services page's 375px breakpoint

---

components/About/WhyUs.vue
tests/__snapshots__/whyUs.spec.js.snap

1. Added new media styles for section

MND-784 adapted Why us section by new design 

---

components/Services/InfrastructureContent.vue
components/Services/ItConsultingContent.vue
components/Services/ItOutsourcing.vue
components/Services/OutsourcingContent.vue
components/Services/SoftwareDevelopContent.vue
components/Services/SoftwareDevelopment.vue

- Fix section title's bug
- Add media queries for small screens and made some small fixes
- Fix icons-list for max-width: 458px and 695px

MND-815-IMPROVE Added media queries for small screens and made some small fixes in the Services page

---

components/About/MeetOurExperts.vue
components/About/MeetOurExpertsMobile.vue
components/About/WhyUs.vue
tests/__snapshots__/meetOurExperts.spec.js.snap
tests/meetOurExpertsMobile.spec.js

1. Adapted section by new design 
2. Fix styles for swiper slider on mobile screens

MND-785 added new media styles for experts section

---

components/About/WeCreateItProjectFor.vue
tests/__snapshots__/weCreateItProject.spec.js.snap

Remove 'Get case studies' button, it's data and fix top padding for the section

MDW-821 Removed 'Get case studies' button and it's data

---

client/components/About/WeCreateItProjectFor.vue
tests/__snapshots__/weCreateItProject.spec.js.snap

- Fix 'We Create IT Projects' section's layout
- Change the order of countries in WeCreateItProjects section

MDW-821-IMPROVE Fixed 'We Create IT Projects section's layout

---

.nuxt/App.js
.nuxt/client.js
.nuxt/components/nuxt-error.vue
.nuxt/components/nuxt.js
.nuxt/index.js
.nuxt/loading.html
.nuxt/mixins/fetch.client.js
.nuxt/mixins/fetch.server.js
.nuxt/router.js
.nuxt/server.js
.nuxt/utils.js
client/components/About/CaseStudies.vue
client/components/About/TechnologiesAndTools.vue
client/components/Banner.vue
client/components/GDPR.vue
client/components/Projects/Customers.vue
client/components/Services/ItOutsourcing.vue

- Fix navigation and paddings of the Customers section
- Fix local links and paddings of the Case Studies component
- Fix paddings of the It Outsourcing section

MDW-857 Fixed navigation and paddings of the Customers, IT Outsourcing and Case Studies sections

---

client/components/About/WeCreateItProjectFor.vue

MDW-821-improve Remove extra paddings

MDW-821-improve Removed extra paddings in the list of countries

---

client/components/Careers/CareersForm.vue
client/plugins/vee-validate.js

- MDW-866 Added validation to the file upload functionality.
- Added validation rules: size and ext.

MDW-866 Added validation to the file upload functionality

---

client/assets/styles/_global.scss
client/assets/styles/_vars.scss
client/components/About/CaseStudies.vue
client/components/About/MeetOurExpertsMobile.vue
tests/__snapshots__/caseStudies.spec.js.snap
tests/__snapshots__/meetOurExperts.spec.js.snap
tests/__snapshots__/meetOurExpertsMobile.spec.js.snap

1. Added pagination dots for experts slider 
2. Added new global styles for pagination dots

MDW-925 added pagination dots for experts slider

---

client/components/About/CustomerTestimonials.vue

Added max-width and width styles

MDW-927 changed container styles for slyder

---

client/assets/styles/_global.scss
client/components/About/CaseStudies.vue
client/components/About/CustomerTestimonials.vue
client/components/About/QuickProjectStart.vue
client/components/About/WeCreateItProjectFor.vue
client/components/About/WhyUs.vue
client/components/Footer.vue
client/components/Header.vue
client/components/Services/InfrastructureContent.vue
client/components/Services/ItConsultingContent.vue
client/components/Services/RemoteTechStaffContent.vue
client/components/Services/SoftwareDevelopContent.vue
client/containers/BannerContainer.vue

Revert "MDW-859"

---

client/components/About/CaseStudies.vue
client/components/About/CustomerTestimonials.vue
client/components/About/MeetOurExperts.vue
client/components/About/WhyUs.vue
client/components/Footer.vue
client/components/GDPR.vue
client/components/NDA.vue
client/components/Projects/OpenSource.vue
client/components/ui/mobile-header.vue
tests/__snapshots__/customerTestimonials.spec.js.snap
tests/__snapshots__/footer.spec.js.snap
tests/__snapshots__/header.spec.js.snap
tests/__snapshots__/indexPage.spec.js.snap
tests/__snapshots__/mobileHeader.spec.js.snap
tests/__snapshots__/openSource.spec.js.snap
tests/__snapshots__/projectsPage.spec.js.snap

Fixes for: 
1. https://pm.maddevs.co/browse/MDW-963
2. https://pm.maddevs.co/browse/MDW-922
3. https://pm.maddevs.co/browse/MDW-998
4. https://pm.maddevs.co/browse/MDW-999
5. https://pm.maddevs.co/browse/MDW-960
6. https://pm.maddevs.co/browse/MDW-961
7. https://pm.maddevs.co/browse/MDW-970

MDW-934 fixed markup bugs

---

client/components/Careers/CareersForm.vue
client/components/Modals/contact-me-modal.vue
tests/careersForm.spec.js

Добавил свои email адреса в две формы для того, чтобы протестировать отправку писем на стейджинге

MDW-935 added new email address for careers form 

---

client/assets/styles/_agreement.scss
client/assets/styles/_global.scss
client/assets/styles/index.scss
client/components/Footer.vue
client/components/Footer/footer-contacts.vue
client/components/Footer/footer-social-network.vue
client/components/GDPR.vue
client/components/NDA.vue
client/components/Privacy.vue
tests/__snapshots__/footer.spec.js.snap
tests/__snapshots__/gdpr.spec.js.snap
tests/__snapshots__/gdprPage.spec.js.snap
tests/__snapshots__/nda.spec.js.snap
tests/__snapshots__/ndaPage.spec.js.snap
tests/__snapshots__/privacy.spec.js.snap
tests/__snapshots__/privacyPage.spec.js.snap

Отрефакторил в относительные величины
Вынес стили в общий файл (т.к они все одинаковые в 99%)

MDW-986 - стили страницы (privacy, GDPR, NDA)

---

client/assets/styles/_global.scss
client/components/Banner/ProjectsBanner.vue
client/components/Careers/Button.vue
client/components/Careers/CareersForm.vue
client/components/Careers/FileInput.vue
client/components/Footer/footer-form.vue
client/components/Projects/Customer.vue
client/components/Projects/Customers.vue
client/components/Projects/OpenSource.vue
client/components/Services/InfrastructureContent.vue
client/components/Services/ItConsultingContent.vue
client/components/Services/ItСonsulting.vue
client/components/ui/UIRadioButtons.vue
tests/__snapshots__/ItConsulting.spec.js.snap
tests/__snapshots__/ItConsultingContent.spec.js.snap

Переделал project, carrer  страницы

Mdw 994 - project, carrer  страницы

---

server.js

Добавил cache-control header для проверки

MDW-873 - cache control

---

server.js

Revert "MDW-873 - cache control"

---

nuxt.config.js

MDW-1109 - async script

---

nuxt.config.js

MDW-1109 - added ssr

---

client/pages/index.vue
nuxt.config.js
package-lock.json
package.json

MDW-1109 - added defer

---

.github/workflows/staging.yml

Added pull new image for staging

---

client/pages/index.vue
nuxt.config.js
package-lock.json
package.json

Revert "MDW-1109 - added defer"

---

client/pages/index.vue
nuxt.config.js

MDW-1109 added defer

---

client/assets/styles/_base.scss
client/components/About/CaseStudies.vue
client/components/About/CustomerTestimonialMobileSlider.vue
client/components/About/CustomerTestimonials.vue
client/components/About/MeetOurExperts.vue
client/components/About/MeetOurExpertsMobile.vue
client/components/About/SingleProject.vue
client/components/About/WhyUs.vue
client/components/Footer/footer-contacts.vue
client/components/Footer/footer-form.vue
client/components/GoDee/Banner.vue
client/components/GoDee/Features.vue
client/components/GoDee/SmartRoutePlaning.vue
client/components/IconsGroup/tech-icon.vue
client/pages/index.vue
tests/__snapshots__/caseStudies.spec.js.snap
tests/__snapshots__/customerTestimonialMobileSlider.spec.js.snap
tests/__snapshots__/customerTestimonials.spec.js.snap
tests/__snapshots__/goDeeBanner.spec.js.snap
tests/__snapshots__/goDeePage.spec.js.snap
tests/__snapshots__/indexPage.spec.js.snap
tests/__snapshots__/meetOurExperts.spec.js.snap
tests/__snapshots__/meetOurExpertsMobile.spec.js.snap
tests/__snapshots__/projectsPage.spec.js.snap
tests/__snapshots__/singleProject.spec.js.snap

Добавил lazy ко всем картинкам на странице
Иправил @fonts

MDW-1109 ленивая загузка

---

client/pages/index.vue
nuxt.config.js

Асинхронность для клатча, удалял, когда были проблемы со стейджем

MDW-1109 added async

---

client/pages/blog/_uid.vue
client/pages/blog/index.vue

Added blocks with schema org snippets

MDW-1718: schema.org snippets to blog

---

client/components/Footer/footer-navbar-mobile.vue
client/components/Footer/footer-navbar.vue
client/components/Footer/footer-social-network-list.vue
client/components/ui/form-checkboxes.vue
tests/__snapshots__/footerContacts.spec.js.snap
tests/__snapshots__/footerSocialNetworkList.spec.js.snap
tests/__snapshots__/formCheckboxes.spec.js.snap

1. Изменил ссылку на блог в футере.<br />Была - https://maddevs.io/blog . <br />Стала - https://medium.com/maddevs-io
2. Поправил ссылки на gdpr, nda, faq и privacy страницы. Нужо было добавить слэш ("/") в конце ссылки

MR-2591 Corrected the gdpr, nda, faq and privacy links for seo. Changed the social link to blog

---

client/components/Footer/footer-navbar-mobile.vue
client/components/Footer/footer-navbar.vue
client/components/Footer/footer-social-network-list.vue
client/components/ui/form-checkboxes.vue
client/pages/blog/_uid.vue
tests/__snapshots__/footerContacts.spec.js.snap
tests/__snapshots__/footerSocialNetworkList.spec.js.snap
tests/__snapshots__/formCheckboxes.spec.js.snap
tests/footerSocialNetworkList.spec.js

Из-за того что Денис и Антон работают над улучшением скорости загрузки сайта и тестируют всё это на стейджинге ( `new-develop` ветка) , деплой на прод сейчас заморожен, а SEOшники ждут фиксы по schema.org и ссылкам по сайту.
В этой ветке находятся фиксы из этих двух PR:
- https://github.com/maddevsio/maddevs/pull/650
- https://github.com/maddevsio/maddevs/pull/654

MR-2597 Fixed the schema.org for posts. Corrected the gdpr, nda, faq and privacy links for seo

---

client/components/About/CustomerTestimonials.vue
tests/__snapshots__/customerTestimonials.spec.js.snap
tests/__snapshots__/indexPage.spec.js.snap

Fixed typo <br />
"Atif Mahmud" - incorrect <br />
"Atif Mahmood" - correct

MR-2619 Fixed typo on the customer's testimonials block. "Atif Mahmood" instead of "Atif Mahmud"

---

client/components/Footer/footer-contacts.vue
tests/__snapshots__/footerContacts.spec.js.snap

Ссылка на messenger в footer компоненте была указана неправильно ( вела на facebook ). Поправил ссылку

MR-2620 Corrected the link to messenger in the footer component

---

client/app/router.scrollBehavior.js
nuxt.config.js

Консоль выводила ошибку о том,  что scrollBehavior функция должна лежать в отдельном файле - `app/router.scrollBehavior.js` <br />
Перенёс эту функцию в соответствии с рекомендацией в документации - https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router#scrollbehavior

MR-2220 Moved the scrollBehavior function into the separate file

---

client/components/Footer/footer-form.vue
nuxt.config.js
server/middleware/rest.js

MR-2637 - refactor middleware path

---

package.json

MR-2662 - removed cleanup command

---

package.json

MR-2662 - Returned cleanup comand with changes

---

README.md
server/middleware/rest.js

Внес небольшие правки по readme 
Добавил редирект со слешем

MR-2660 - Updated readme and added redirect

---

server/json/customer-university.json
server/json/redirect.json
server/middleware/rest.js

Вынес конфиг редиректа в отдельный файл, так как redirect.json несколько не соответствует этим редиректам

MR-2020 - changed redirect logic

---

client/components/Blog/RecommendedBlogWidget.vue
client/pages/blog/index.vue
tests/__snapshots__/recommendedBlogWidget.spec.js.snap

Исправил позицию скролла до недавнего поста,  по которому юзер переходил со страницы блога.
Теперь скролл возвращается на позицию поста,   по которому был переход

MR-2220 Fixed the scroll position for posts on the blog page

---

client/static/sitemap.xml
nuxt.config.js
package.json
server/middleware/rest.js

1. Обновил heroku-cleanup скрипт, сделал так чтобы папка static не удалялась при билде 
2. Обновил сайтмап файл, добавил в него новые ссылки 
3. Обновил логику с редиректами, сделал так чтобы конечный слеш не подставлялся для URL есть тот содержит sitemap.xml

New develop to master update bash script and sitemap.xml file

---

client/components/Blog/CuNavigation.vue
client/components/Blog/PostView.vue
client/components/Blog/RecommendedBlogWidget.vue
client/components/Modals/contact-me-modal.vue

Буллеты выровнял по основному тексту
Убрал паддинги для разрешения менее 1024
изменил тип background для картинок

MR-2527 - fix blog items

---

client/assets/styles/cases/sir-john-monash-centre/_styles.scss
client/pages/case-studies/namba-food.vue
client/pages/case-studies/sir-john-monash-centre.vue
tests/__snapshots__/caseNambaFood.spec.js.snap
tests/__snapshots__/caseSJMC.spec.js.snap

1) Поправил тайтл и описание для кейсов ( взял из дизайна )
2) Поправил выравнивание логотипа в хедере кейса

MR-2153 Corrected title and description in the header of Nambafood and SJMC cases

---

client/components/ui/BeforeAfterImage.vue

Если приглядеться очень хорошо,  картинка слегка смещалась в сторону при свайпе вправо на 100%. Поправил одну строчку стилей

MR-2106 Corrected size for BeforeAfterImage component

---

client/assets/styles/_base.scss
client/assets/styles/cases/_base.scss
nuxt.config.js

1. В рамках ПР-а исправил импорт шрифта inter, импортнул его в глобальный файл, так как шрифт используется в блоге и кейсах 
2. Добавил новый мета тег в head тег

MR-2812 added global import for Inter and added new meta tag in head tag

---

client/assets/styles/cases/godee/_styles.scss
client/pages/case-studies/godee.vue

Поправил разметку для GoDee кейса ( завернул CaseHeader компонент в content_layer блок )

MR-2022 Corrected the parallax layers for GoDee case

---

client/pages/blog/_uid.vue
client/pages/customer-university/_uid.vue
server/json/blog.json
server/middleware/rest.js

https://pm.maddevs.co/browse/MR-2595 - таск
1) Была проблема с тем,  что на одну и ту же статью можно переходить по разным URL:
- https://maddevs.io/blog/top-3-best-ci-for-your-js-projects-with-puppeteer-tests/
- https://maddevs.io/blog/best-ci-for-js-projects-with-puppeteer-tests/
Это потому что для неё меняли UID поле,  а призмик сохраняет прошлые UID поля у себя и по ним тоже можно запросить этот пост. Тут инфа: https://community.prismic.io/t/when-does-cache-expire-uid-history/874/14
<br /> Добавил проверку на текущий указанный в призмике UID . Теперь редиректит на ссылку с текущим UID поста
2) Добавил редирект для удалённого поста, который возвращал 404 - https://maddevs.io/blog/web-app-deploy-to-glitch-com/ на эту же статью, которая опубликована

MR-2595 Fixed the with duplicate url for one article, added the new redirect for deleted blog article

---

client/components/Blog/slices/CodeBlockSlice/index.vue

https://www.loom.com/share/74bcb131b9c54cb9b189b2101dab50fc - проблема
Немного неправильно порефакторили компонент,  поправил метод для страницы поста, который ломался

MR-2595 Fixed a bug with breaking the post page when going to it via a direct link

---

client/pages/blog/_uid.vue
client/pages/customer-university/_uid.vue

Задача - https://maddevs.atlassian.net/browse/MAR-182
Немного порефакторил код _uid.vue страниц для постов.  Дополнил пару проверок

MAR-182 Refactored the code for CU _uid and blog _uid pages

---

client/pages/blog/_uid.vue
client/pages/customer-university/_uid.vue

Задача - https://maddevs.atlassian.net/browse/MAR-495
**Проблема:**
Не рендерится meta_title и meta_description для постов
**Решение:**
Поправил вывод мета данных

MAR-495 Fixed the output of metadata for posts

---

client/components/Blog/RecommendedBlogWidget.vue

Поправил отступ от картинки до названия поста в RecommendedBlogWidget компоненте

MAR-77 Corrected indents of preview image in the blog items

---

client/components/Cases/godee/BeforeAfter.vue
client/components/Cases/godee/PreviewCards.vue
client/components/Cases/godee/RealTimeETA.vue

https://maddevs.atlassian.net/browse/MAR-569
* Поправил стили для секций с темным бэкграундом
* Поправил urls для картинок в BeforeAfterImage

MAR-569. Issues with GoDee case

---

client/components/core/Header/Header.vue

MAR-579. Fixed bug with `Contact me` button

---

client/components/core/Header/Header.vue
client/components/core/Header/HeaderLogo.vue

1. Поменял анимацию для хедера, когда он меняет цвет на черный.
2. Поправил логику для функции смены цвета

MAR-578 changed animation for header

---

client/components/Blog/slices/EmbedSlice.vue
client/components/Blog/slices/TextSlice.vue
tests/components/Blog/slices/EmbedSlice.spec.js

Починил проблему с кривыми регулярками(Не работают в сафари). Порефакторил код, чтобы избавиться от кучи `replace`'ов в пользу сборки html при помощи шаблонных строк

MAR-669. Fixed bugs with blog posts on iPhone

---

client/components/Careers/Careers.vue
client/components/Careers/FileInput.vue

1. Удалил delay для модального, которое появляется после успешной отправки формы, чтобы можно было закрыть форму только нажав на крестик
2. Вернул метод reset для ModalSuccess. кто-то удалил

MAR-489 removed delay for Career form

---

client/components/core/forms/BaseForm.vue
client/components/core/forms/FooterForm.vue
client/directives/PlaceholderAsterisk.js

* Вернул звездочку
* Проверил работоспособность формы
* Убрал required с поля fullname

MAR-675. Returned required to footer form.

---

.env.example
README.md
client/featureFlags/Feature.vue
client/featureFlags/config.js
client/featureFlags/featureFlag.js
client/featureFlags/index.js
client/plugins/feature-flags.js
nuxt.config.js

* Разработал плагин для работы с feature-флагами
* Добавил описание флагов в readme

MAR-676. Feature flags

---

client/components/Careers/Careers.vue

Починил проблему с отправкой некорректных данных в форме careers, проблема заключалась в поле positionValue(grade)

MAR-687. Issue with careers form

---

client/assets/styles/cases/sir-john-monash-centre/_styles.scss
client/components/Cases/sjmc/Hardware.vue
tests/__snapshots__/caseSJMC.spec.js.snap
tests/components/Cases/sjmc/__snapshots__/Hardware.spec.js.snap

* Поправил верстку с телефоном

MAR-689. Issue with markup in SJMC case

---

client/assets/styles/cases/yourcast/_styles.scss
client/components/Blog/Post/Post.vue
client/components/Cases/shared/CaseHeader.vue
client/components/core/Header/Header.vue
client/components/core/Header/HeaderMobile.vue
client/data/caseStudies.js
client/helpers/playLottie.js
client/mixins/autoplayVideoMixin.js
client/pages/case-studies/godee.vue
client/pages/case-studies/namba-food.vue
client/pages/case-studies/sir-john-monash-centre.vue
tests/__snapshots__/caseNambaFood.spec.js.snap
tests/__snapshots__/caseSJMC.spec.js.snap
tests/components/core/Header/Header.spec.js
tests/components/core/Header/MobileHeader.spec.js
tests/components/core/Header/__snapshots__/Header.spec.js.snap
tests/components/core/Header/__snapshots__/MobileHeader.spec.js.snap

- Пофиксил большую часть ошибок из сентри
- В процессе фикса нашел баг со стилями в фоновом видео у кейсов(не применялись нужные стили) - поправил

MAR-698. Fixed bugs from sentry

---

client/components/core/forms/BaseForm.vue
client/components/core/forms/BaseInput.vue
client/components/core/forms/GetExpertAdviceForm.vue
client/components/core/forms/GetYourTrustedItPartnerForm.vue
client/components/core/forms/IndividualsForm.vue
client/helpers/validators.js
client/mixins/phoneHandlerMixin.js
tests/components/core/Footer/__snapshots__/Footer.spec.js.snap
tests/components/core/forms/BaseInput.spec.js
tests/components/core/forms/__snapshots__/BaseInput.spec.js.snap
tests/components/core/modals/ModalContactMe.spec.js
tests/components/core/modals/ModalGetExpertAdvice.spec.js
tests/components/core/modals/ModalGetYourTrustedItPartner.spec.js
tests/components/core/modals/ModalIndividuals.spec.js
tests/components/core/modals/ModalInfrastructureAudit.spec.js
tests/components/core/modals/ModalOrderProjectFromUs.spec.js
tests/components/core/modals/ModalTeams.spec.js
tests/components/core/modals/__snapshots__/ModalContactMe.spec.js.snap
tests/components/core/modals/__snapshots__/ModalGetExpertAdvice.spec.js.snap
tests/components/core/modals/__snapshots__/ModalGetYourTrustedItPartner.spec.js.snap
tests/components/core/modals/__snapshots__/ModalIndividuals.spec.js.snap
tests/components/core/modals/__snapshots__/ModalInfrastructureAudit.spec.js.snap
tests/components/core/modals/__snapshots__/ModalOrderProjectFromUs.spec.js.snap
tests/components/core/modals/__snapshots__/ModalTeams.spec.js.snap
tests/mixins/phoneHandler.spec.js

* Добавил компонент BaseInput, который реализует всю логику работы инпута, включая отображение ошибок, лейблов и т.д.
* Заюзал компонент BaseInput во всех формах, включая BaseForm
* Прогнал тесты и апдейтнул их
* Проверил все формы, сравнил с поведением на стейджинге

MAR-684. Added BaseInput component

---

client/components/Blog/slices/TextSlice.vue
client/components/Cases/shared/CaseHeader.vue
client/components/Cases/shared/TextParagraph.vue
client/components/Cases/yourcast/CardProjectMilestone.vue
client/components/shared/UIBeforeAfterImage.vue

Удалил все использования $props

MAR-702. Replaced all $props calls.

---

client/components/Blog/slices/SimpleModal.vue
client/components/core/Modal.vue

Увеличил z-index модалки, что бы перекрыть  intercom
Как понизить интеркомовский index  в доке не нашёл

MAR-729 - changed zindex

---

client/components/Blog/Post/Post.vue

Поправил позици кнопки "наверх" , которая появляется в левом нижнем углу на странице поста

MAR-729 Fixed position of back to top button

---

client/components/Cases/godee/Main.vue
client/pages/case-studies/godee.vue
tests/components/Cases/godee/Main.spec.js
tests/components/Cases/godee/__snapshots__/Main.spec.js.snap

При рефакторинге кейса, вёрстку с параллакс эффектом обернули в лишний див со своими стилями,  которые его сломали
Убрал лишний html узел
https://www.loom.com/share/b3ed93d674e84f2599a72bf98d23d86d
В Firefox из-за обёртки <section></section> не работал параллакс, убрал лишний узел путём переноса вёрстки в Main компонент

MAR-539 Fixed parallax effect which was broken after code refactoring in GoDee case ( Safari and Firefox browsers )

---

client/components/core/forms/ContactMeForm.vue
client/components/core/forms/FooterForm.vue
client/components/core/forms/GetExpertAdviceForm.vue
client/components/core/forms/GetYourTrustedItPartnerForm.vue
client/components/core/forms/IndividualsForm.vue
client/components/core/forms/InfrastructureAuditForm.vue
client/components/core/forms/OrderProjectFromUsForm.vue
client/components/core/forms/TeamsForm.vue
client/mixins/createNewLeadMixin.js

* Добавил amoCRM во все формы на сайте
* Немного поменял структуру поля description, при помощи которого создается заметка. Теперь туда передается название поля и значение
* Добавил метод buildLeadDescription в createNewLeadMixin

Added amoCRM to another forms on the website.

---

client/components/Blog/Main/AllPostsSection.vue
client/components/Blog/shared/RecommendedBlogWidget.vue

Задача - https://maddevs.atlassian.net/browse/MAR-630
Поправил медиа стили для первью картинок постов на странице блога ( секция с фильтром по постам )
Сделал их побольше для маленьких экранов

MAR-630 Corrected the image size of the blog posts for small screens

---

client/components/Cases/nambafood/AdminPanel.vue
client/components/Cases/nambafood/CouriersApplication.vue
client/components/Cases/nambafood/Grafana.vue
client/components/Cases/nambafood/Pipelines.vue
client/components/Cases/sjmc/Hardware.vue
client/components/Cases/sjmc/MobileApplications.vue
client/components/Cases/sjmc/Partnership.vue
client/components/Cases/sjmc/Software.vue
client/components/Cases/sjmc/SystemMonitoring.vue
client/components/Cases/sjmc/TeamIssues.vue
tests/__snapshots__/caseNambaFood.spec.js.snap
tests/__snapshots__/caseSJMC.spec.js.snap
tests/components/Cases/namba-food/__snapshots__/AdminPanel.spec.js.snap
tests/components/Cases/namba-food/__snapshots__/CouriersApplication.spec.js.snap
tests/components/Cases/namba-food/__snapshots__/Grafana.spec.js.snap
tests/components/Cases/namba-food/__snapshots__/Pipelines.spec.js.snap
tests/components/Cases/sjmc/__snapshots__/Hardware.spec.js.snap

Added props width & height for components Picture

MAR-660 added width & height by default for images

---

client/components/Blog/Main/AllPostsSection.vue
client/components/Blog/shared/PostAuthor.vue
client/components/Blog/shared/PostTag.vue
client/components/Blog/shared/RecommendedBlogWidget.vue
tests/components/Blog/Main/__snapshots__/AllPostsSection.spec.js.snap
tests/components/Blog/Main/__snapshots__/Main.spec.js.snap
tests/components/Blog/Main/__snapshots__/TheLastPostSection.spec.js.snap
tests/components/Blog/header/__snapshots__/Blog.spec.js.snap
tests/components/Blog/shared/__snapshots__/FeaturedPost.spec.js.snap
tests/components/Blog/shared/__snapshots__/PostTag.spec.js.snap
tests/components/Blog/shared/__snapshots__/RecommendedBlogWidget.spec.js.snap

Поправил отступы у картинки поста
Поправил классы для PostAuthor и PostTag компонентов

MAR-630 Corrected indents for RecommendedPostWidget component

---

client/assets/styles/_global.scss
client/assets/styles/_vars.scss
client/components/core/Footer/FooterContacts.vue
client/components/core/Footer/FooterNavbar.vue
client/components/core/forms/BaseForm.vue
client/components/core/forms/FooterForm.vue
client/components/shared/UIFormCheckboxes.vue
tests/components/core/Footer/__snapshots__/Footer.spec.js.snap
tests/components/core/modals/__snapshots__/ModalContactMe.spec.js.snap
tests/components/core/modals/__snapshots__/ModalGetExpertAdvice.spec.js.snap
tests/components/core/modals/__snapshots__/ModalGetYourTrustedItPartner.spec.js.snap
tests/components/core/modals/__snapshots__/ModalIndividuals.spec.js.snap
tests/components/core/modals/__snapshots__/ModalInfrastructureAudit.spec.js.snap
tests/components/core/modals/__snapshots__/ModalOrderProjectFromUs.spec.js.snap
tests/components/core/modals/__snapshots__/ModalTeams.spec.js.snap
tests/components/shared/__snapshots__/UIFormCheckboxes.spec.js.snap

1. Обновил стили для формы в футере 
2. Обновил шрифты для всего футера

MAR-754 update styles for footer

---

client/components/Blog/Main/AuthorBanner.vue
client/components/Blog/Main/AuthorPostsSection.vue
client/components/Blog/Main/CustomerUniversitySection.vue
client/components/Blog/Main/TagPostsSection.vue
client/components/Blog/shared/FeaturedPost.vue
client/components/Blog/shared/PostAuthor.vue
tests/components/Blog/Main/__snapshots__/TheLastPostSection.spec.js.snap
tests/components/Blog/shared/__snapshots__/FeaturedPost.spec.js.snap

1) Поправил вывод featured поста на странице автора и теговой странице
2) Поправил вёрстку страниц

MAR-137 Fixes for the tag and author pages

---

client/components/Blog/Main/AuthorPostsSection.vue
client/components/Blog/Main/TagPostsSection.vue
client/components/Blog/slices/AuthorSlice.vue

1) Поправил вёрстку
2) Поправил кол-во вывода постов на страницу

MAR-137 Minor fixes for tag and author blog pages

---

client/components/Cases/sjmc/SJMCVideo.vue
client/components/core/Footer/FooterContacts.vue
client/components/core/forms/FooterForm.vue
client/components/shared/UIButton.vue
tests/__snapshots__/caseSJMC.spec.js.snap
tests/components/Cases/__snapshots__/SJMCVideo.spec.js.snap
tests/components/core/Footer/__snapshots__/Footer.spec.js.snap

1. Удалил lazy у fullscreen видео в кейсе - он там не нужен, к тому же это приводит к ошибкам 
2. Поправил стили для формы в футере, вынес стили в компонент кнопки, чтобы они применялись корректно

MAR-773 remove lazy from video in SJMC case and update styles for submit button in footer

---

client/data/seo.js
client/helpers/extractSchemaOrg.js
client/mixins/buildPostPageMixin.js
client/pages/blog/author/_uid/index.vue
client/pages/blog/tag/_uid/index.vue
client/store/modules/blogAuthors.js
tests/pages/careers.spec.js
tests/pages/faq.spec.js
tests/pages/gdpr.spec.js
tests/pages/index.spec.js
tests/pages/nda.spec.js
tests/pages/privacy.spec.js
tests/pages/projects.spec.js
tests/pages/services.spec.js

1) Добавил дополнительные настройки в buildHead() скрипт в файле data/seo.js
2) Добавил мета данные для теговой страницы и страницы автора
buildHead для теговой не до конца заполнен, нужны от Зайтуны тайтл и описание. Можно пока так залить, не критично

MAR-137 Improved the buildHead seo script for pages, added the meta data for the author and tag pages

---

client/components/Blog/Main/AuthorPostsSection.vue
client/components/Blog/Main/TagPostsSection.vue
client/components/Blog/shared/PostAuthor.vue
client/components/Blog/shared/PostTag.vue
client/components/Blog/shared/RecommendedBlogWidget.vue
client/data/seo.js
client/pages/blog/author/_uid/index.vue
client/pages/blog/index.vue
client/pages/blog/tag/_uid/index.vue
tests/components/Blog/Main/__snapshots__/AllPostsSection.spec.js.snap
tests/components/Blog/Main/__snapshots__/Main.spec.js.snap
tests/components/Blog/Main/__snapshots__/TheLastPostSection.spec.js.snap
tests/components/Blog/header/__snapshots__/Blog.spec.js.snap
tests/components/Blog/shared/__snapshots__/FeaturedPost.spec.js.snap
tests/components/Blog/shared/__snapshots__/PostTag.spec.js.snap
tests/components/Blog/shared/__snapshots__/RecommendedBlogWidget.spec.js.snap

1) Поправил вывод мета данных в head() для страниц блога
2) Добавил disabled state для ссылок на автора и на теговую страницу

MAR-137 Corrected the meta data for blog pages, added the disabled state for theauthor and tag links

---

client/components/core/forms/BaseForm.vue

1. Добавил условие при котором кнопка в формах будет не доступна в момент отправки формы и запроса на сервер

MAR-809 added new condition for disabled attribute

---

client/components/shared/UIBeforeAfterImage.vue

1) При touchmove Before&After компонент не менял положение картинки. Поправил хэндлеры

MAR-808 Fixed the touch handlers for the Before&After component

---

client/assets/styles/cases/godee/_styles.scss
client/components/Cases/godee/Main.vue
tests/components/Cases/godee/__snapshots__/Main.spec.js.snap

1)  Поправил верхний пэддинг первой секции с контентом - GoDee кейс
2) Поправил размер изображения в секции Real-time ETA - Godee кейс

MAR-812 Fixed paddings of the first content layer section in GoDee case

---

client/data/caseSJMC.js
tests/__snapshots__/caseSJMC.spec.js.snap

1. Добавил в S3 новые картинки и удалил старые, нужно залить хотфикс чтобы не было ошибки на проде об отсутствии одной из удаленных картинок

MAR-788 update slider list HOT-FIX

---

client/components/Blog/slices/TextSlice.vue

Некорректно был прописан шрифт в стилях. Поправил строчку font-family

MAR-835 Fixed the font displaying for the strong tags in the TextSlice component

---

client/assets/styles/cases/godee/_styles.scss
client/components/Cases/godee/RealTimeETA.vue
tests/components/Cases/godee/__snapshots__/Main.spec.js.snap
tests/components/Cases/godee/__snapshots__/RealTimeETA.spec.js.snap

Задача - https://maddevs.atlassian.net/browse/MAR-567
Добавлена ссылка для секции в  GoDee кейсе, которая ведёт на определённую статью

MAR-567 "Find out more" link-button for the "Real-time ETA" section in GoDee case

---

client/helpers/extractSchemaOrg.js
client/helpers/getRoutesList.js
nuxt.config.js

Generate скрипт получал неправильный список роутов и не полный. Обновил список роутов, порефакторил сам скрипт

MAR-848  Changed the generate method in the nuxt.config file

---

client/components/Cases/sjmc/HardwareVideo.vue

1. Убрал лишние стили у блока с видосом

MAR-874 update styles for SJMC phone video

---

client/components/Cases/BuildDevTeam.vue
tests/layouts/__snapshots__/default.spec.js.snap
tests/layouts/__snapshots__/error-layout.spec.js.snap
tests/layouts/__snapshots__/error.spec.js.snap
tests/layouts/__snapshots__/godee.spec.js.snap
tests/layouts/default.spec.js
tests/layouts/error-layout.spec.js
tests/layouts/error.spec.js
tests/layouts/godee.spec.js

MAR - 804 - layouts tests

---

client/assets/styles/_vars.scss
client/components/Blog/skeletons/SkeletonBlogWidget.vue
client/components/Blog/skeletons/SkeletonFeaturedPost.vue
tests/components/Blog/skeleton/__snapshots__/SkeletonBlogWidget.spec.js.snap

Исправил анимацию
Добавил анимацию для верхнего блока

MAR - 290 - Skeleton-loader

---

client/assets/styles/_vars.scss
client/components/Cases/shared/CaseHeader.vue
client/components/core/Header/Header.vue
client/pages/case-studies/sir-john-monash-centre.vue
jest/base.config.js
tests/__snapshots__/caseNambaFood.spec.js.snap
tests/__snapshots__/caseSJMC.spec.js.snap
tests/components/Cases/godee/__snapshots__/Main.spec.js.snap
tests/components/Cases/shared/CaseHeader.spec.js
tests/components/Cases/shared/__snapshots__/CaseHeader.spec.js.snap
tests/components/core/Header/Header.spec.js
tests/pages/case-studies/__snapshots__/namba-food.vue.spec.js.snap
tests/pages/case-studies/__snapshots__/sir-john-monash-centre.spec.js.snap
tests/pages/case-studies/__snapshots__/veeqo.spec.js.snap
tests/pages/case-studies/__snapshots__/yourcast.spec.js.snap

Добавил градиент для прозрачного header
Добавил opacity по скролу
Добавил тесты
Поднял условия по coverage

MAR-837 - Header gradient

---

client/assets/styles/_vars.scss
client/components/Cases/shared/CaseHeader.vue
client/components/Cases/shared/StatisticsContainer.vue
client/components/Cases/shared/StatisticsItem.vue
client/components/Cases/veeqo/About.vue
client/data/caseVeeqo.js
client/pages/case-studies/veeqo.vue
tests/components/Cases/shared/StatisticsContainer.spec.js
tests/components/Cases/shared/StatisticsItem.spec.js
tests/components/Cases/shared/__snapshots__/StatisticsContainer.spec.js.snap
tests/components/Cases/shared/__snapshots__/StatisticsItem.spec.js.snap
tests/components/Cases/veeqo/__snapshots__/About.spec.js.snap
tests/components/Cases/veeqo/__snapshots__/Main.spec.js.snap
tests/pages/case-studies/__snapshots__/veeqo.spec.js.snap
tests/pages/case-studies/veeqo.spec.js

1. Добавил стили для и нужные медиа файлы для баннера с видео 
2. Добавил новые переиспользуемые компоненты

MAR-921 added styles for Banner and new shared component

---

client/components/Cases/sjmc/SJMCVideo.vue
client/store/modules/blog.js
tests/components/Cases/SJMCVideo.spec.js

Добавил условие для data 
Добавил обраточики ошибок
Дописал тесты

MAR-985 - Правки по ошибкам в Sentry

---

client/components/core/forms/ContactMeForm.vue
client/components/core/forms/FooterForm.vue
client/components/core/forms/GetExpertAdviceForm.vue
client/components/core/forms/GetYourTrustedItPartnerForm.vue
client/components/core/forms/IndividualsForm.vue
client/components/core/forms/InfrastructureAuditForm.vue
client/components/core/forms/OrderProjectFromUsForm.vue
client/components/core/forms/TeamsForm.vue
client/mixins/createNewLeadMixin.js
jest/base.config.js

Удалили запрос на amoCrm
Закоментил миксин 
Остальной функционал оставил без изменения

MAR-995 - removed query

---

client/assets/styles/_base.scss
client/components/Blog/Post/Post.vue
client/components/Blog/slices/CodeBlockSlice/index.vue
client/components/Blog/slices/GithubGistSlice.vue
client/components/Blog/slices/TextSlice.vue

* Добавил шрифт IBM для блоков кода

MAR-1006. Added IBM Plex Mono font for code snippets.

---

client/components/Careers/shared/PositionForm.vue
client/components/Careers/shared/PositionHeader.vue

- Поправил line-height для заголовка страницы
- Поправил вложенность селекторов в стилях

MAR-441 Minor fixes for Career page

---

client/assets/styles/_global.scss

MAR-85 - changed error colours

---

client/api/careers.js
client/assets/styles/_global.scss
client/components/Careers/shared/Careers.vue
client/components/Careers/shared/PositionForm.vue
client/store/modules/careers.js
jest/base.config.js
server/controllers/CareersController.js
server/routes/api.js
server/utils/validation.js
tests/components/Careers/shared/Careers.spec.js
tests/components/Careers/shared/PositionForm.spec.js

Deploy to production

---

client/store/modules/careers.js
jest/base.config.js
tests/api/careers.spec.js
tests/components/Careers/CTABanner.spec.js
tests/components/Careers/OpenPositions.spec.js
tests/components/Careers/__snapshots__/CTABanner.spec.js.snap
tests/components/Careers/__snapshots__/OpenPositions.spec.js.snap
tests/components/Careers/shared/PositionsFilter.spec.js
tests/components/Careers/shared/PositionsGrid.spec.js
tests/components/Careers/shared/PositionsGridItem.spec.js
tests/components/Careers/shared/ScrollToPositionsButton.spec.js
tests/components/Careers/shared/UnderlinedButton.spec.js
tests/components/Careers/shared/__snapshots__/PositionsFilter.spec.js.snap
tests/components/Careers/shared/__snapshots__/PositionsGrid.spec.js.snap
tests/components/Careers/shared/__snapshots__/PositionsGridItem.spec.js.snap
tests/components/Careers/shared/__snapshots__/ScrollToPositionsButton.spec.js.snap
tests/components/Careers/shared/__snapshots__/UnderlinedButton.spec.js.snap
tests/components/shared/UIBanner.spec.js
tests/components/shared/__snapshots__/UIBanner.spec.js.snap
tests/store/careers.spec.js

1) Добавил для компонентов недостающие unit-тесты
2) Вернул на место coverageThreshold в конфиге тестов ( снижал его на время, для деплоя на стейжинг )

MAR-958 Unit-tests for careers page

---

client/components/Careers/EmployeesBenefits.vue
client/components/Careers/OpenPositions.vue
client/components/Careers/shared/BenefitCard.vue
client/components/Careers/shared/PositionsFilter.vue
client/components/Careers/shared/ScrollToPositionsButton.vue
client/pages/careers/_uid.vue
client/store/modules/careers.js
jest/base.config.js
tests/components/Careers/OpenPositions.spec.js
tests/components/Careers/__snapshots__/CTABanner.spec.js.snap
tests/components/Careers/__snapshots__/OpenPositions.spec.js.snap
tests/components/Careers/shared/ScrollToPositionsButton.spec.js
tests/components/Careers/shared/__snapshots__/BenefitCard.spec.js.snap
tests/components/Careers/shared/__snapshots__/ScrollToPositionsButton.spec.js.snap
tests/pages/careers/__snapshots__/_uid.spec.js.snap
tests/store/careers.spec.js

1) Добавил условие для vacancyCategories геттера, чтобы он не отдавал категории в которых нет постов
2) Добавил reset категории при повторном клике
3) Починил отображение сетки бенефитов

MAR-1083 Filtered the output of vacancyCategories from vuex store, added the reset logic to category, fixed benefits grid layout

---

client/components/Blog/Main/PostsSection.vue
client/components/Blog/Main/SearchResultBanner.vue
client/components/Blog/Post/TableOfContents.vue
client/components/core/modals/ModalSearch.vue
client/components/slices/index.vue
client/pages/blog/search-result/index.vue

1. Added sort for search posts
2. Moved search query to url from localStorage
3. Minor fixes

MAR-556 fixed linter error

---

client/components/Careers/shared/PositionForm.vue
client/components/Careers/shared/PositionHeader.vue
client/components/Careers/shared/PositionsGridItem.vue
client/components/Careers/shared/ScrollToPositionsButton.vue
client/components/core/modals/ModalSearch.vue
client/mixins/scrollToElementMixin.js
client/pages/blog/search-result/index.vue
client/pages/careers/_uid.vue
client/store/modules/careers.js
tests/components/Careers/shared/__snapshots__/PositionForm.spec.js.snap
tests/components/Careers/shared/__snapshots__/PositionHeader.spec.js.snap
tests/components/Careers/shared/__snapshots__/ScrollToPositionsButton.spec.js.snap
tests/mixins/scrollToElement.spec.js
tests/pages/careers/__snapshots__/_uid.spec.js.snap

1) Поправил отображение заголовка карточки вакансии
2) Поправил скролл с помощью кнопок до списка вакансий и формы отправки заявки
3) Добавил мета теги для страницы вакансии
4) Поправил стили для формы отправки
5) Поправил условие в careers vuex store

MAR-1085 Minor fixes for Careers pages

---

babel.config.js
client/components/Blog/Post/TableOfContents.vue
client/components/core/modals/ModalSearch.vue
client/mixins/mainMixins.js
jest/base.config.js
tests/components/Blog/Post/TableOfContents.spec.js
tests/components/core/modals/ModalSearch.spec.js
tests/mixins/mainMixins.spec.js

* Added auto scroll for Table of Contents
* Added test for Table of Contents
* Added tests for func createAnchorLink

MAR-558 Fixes for Table of Contents

---

client/components/Careers/shared/PositionsGridItem.vue
client/components/Cases/CasesList.vue
client/components/Cases/sjmc/SJMCVideo.vue
client/components/Cases/yourcast/CardProjectMilestone.vue
client/data/tagPagesSeo.js
client/helpers/playLottie.js
client/mixins/autoplayVideoMixin.js

1. Добавил try catch блоки для хэндлеров - https://sentry.io/organizations/mad-devs-lh/issues/2408303547/?referrer=slack
2. Поправил мета данные для теговых страниц

MAR-1115 Fixed catch callbacks for lottie animation handlers

---

client/assets/styles/_vars.scss
client/components/Cases/veeqo/CardResult.vue
client/components/Cases/veeqo/ContinuousIntegrationResult.vue
client/components/Cases/veeqo/HighLevelOverview.vue
client/components/Cases/veeqo/InventoryChangeLog.vue
client/components/Cases/veeqo/PhasInfrastructureAsCodeResult.vue
client/components/Cases/veeqo/PhaseElasticsearchResult.vue
client/data/animationConfigs.js
client/data/caseVeeqo.js
client/plugins/vue-prlx.js
nuxt.config.js
package-lock.json
package.json
tests/components/Cases/veeqo/ContinuousIntegrationResult.spec.js
tests/components/Cases/veeqo/__snapshots__/CardResult.spec.js.snap
tests/components/Cases/veeqo/__snapshots__/ContinuousIntegrationResult.spec.js.snap
tests/components/Cases/veeqo/__snapshots__/HighLevelOverview.spec.js.snap
tests/components/Cases/veeqo/__snapshots__/InventoryChangeLog.spec.js.snap
tests/components/Cases/veeqo/__snapshots__/Main.spec.js.snap
tests/components/Cases/veeqo/__snapshots__/PhasInfrastructureAsCodeResult.spec.js.snap
tests/components/Cases/veeqo/__snapshots__/PhaseElasticsearchResult.spec.js.snap

1. Added new plugin for animation, demo: http://vue-prlx.surge.sh/.
2. Added styles for new blue cards in Veeqo case
3. Added animation params for elements for elements in Veeqo case

MAR-1124 added animation for Veeqo case

---

client/api/careers.js
client/components/Careers/shared/PositionsGrid.vue
tests/components/Careers/shared/__snapshots__/PositionsGrid.spec.js.snap

Поправил порядок вакансий в списке на странице Careers, чтобы более свежие вакансии были в самом верху списка

MAR-1159 Fixed ordering of vacancies list

---

client/components/Blog/header/Common.vue
tests/components/Blog/header/__snapshots__/Blog.spec.js.snap
tests/components/Blog/header/__snapshots__/Common.spec.js.snap

1. Чуть поменял computed метод, добавил для URL-а картинки параметр, он указывает на сколько процентов нужно сжать картинку от изначального значения 
2. Параметры для URL-а смотрел вот тут, этот сервис используется призмиком для работы с картинками: https://imgix.com/solutions/compression-and-performance

MAR-1059 added compress params for img url

---

client/components/Blog/header/Common.vue
tests/components/Blog/header/__snapshots__/Blog.spec.js.snap
tests/components/Blog/header/__snapshots__/Common.spec.js.snap

1. Удалил настройки качества для обложек блог постов. Теперь они не буду сжиматся

Update quality settings for blog post featured images

---

client/components/Blog/header/Common.vue
client/mixins/buildBlogPostMixin.js
nuxt.config.js
tests/components/Blog/header/__snapshots__/Blog.spec.js.snap
tests/components/Blog/header/__snapshots__/Common.spec.js.snap

1. Добавил настройку которая выставляет кастомный процент сжатия картинок в блог постах и их превью картинок
2. Добавил новый конфиг для nuxt router-а, он нужен для того чтобы к каждой ссылке добавлялся конечный слеш
Вот задачи которые решает этот ПР: https://maddevs.atlassian.net/browse/MAR-1408, https://maddevs.atlassian.net/browse/MAR-1381

MAR-1408 added quality settings for images and config for router

---

client/data/deliveryModels.js
tests/components/DeliveryModels/__snapshots__/ModelsGrid.spec.js.snap

Правки по тексту https://docs.google.com/document/d/1ilzCTc3JeI7ahVvLXrf8TYIifWbT8yTQ8FD1GK4DkTY/edit?usp=sharing 
В доке только правильные формулировки. Их нужно вставить

MAR-1409 Typo fixes for DM page

---

client/components/Blog/Post/Post.vue
client/components/Blog/header/Common.vue
client/components/core/Header/Header.vue
tests/components/Blog/Post/Post.spec.js
tests/components/Blog/Post/__snapshots__/Post.spec.js.snap
tests/components/Blog/header/__snapshots__/Blog.spec.js.snap
tests/components/Blog/header/__snapshots__/Common.spec.js.snap
tests/components/core/Header/__snapshots__/Header.spec.js.snap

1. Переписал логику которая добавляет для table of content блока свойство sticky 
2. Покрыл тестами весь новый код

MAR-742 update scrollHandler method in Post.vue component

---

client/components/slices/index.vue
client/helpers/convertTagsToText.js
client/helpers/getFirstParagraph.js
tests/helpers/convertTagsToText.spec.js

Сделал хелпер функцию, которая ищет все теги в тексте и переводит их в текстовый формат, чтобы они не рендерились браузером

MAR-1393 Fixed a bug with broken blog posts due to html tags in the text

---

nuxt.config.js
package-lock.json
package.json

1. Обновил способ подключения GTM на страницы сайта, старый способ не работал и я избавился от него

MAR-1441 update GTM connection logic

---

client/components/Careers/shared/PositionForm.vue
client/mixins/createLeadMixin.js
tests/components/Careers/shared/PositionForm.spec.js

Добавил новую переменную pageUrl со ссылкой на страницу, с которой была отправлена форма

MAR-1560 Updated variables for email leads

---

client/components/Careers/shared/PositionForm.vue
client/components/DeliveryModels/Banner.vue
client/mixins/createLeadMixin.js
tests/components/Careers/shared/PositionForm.spec.js

Изменил одну строчку стилей для DM страницы
Синхронизировал develop с master

MAR-1400 Minor layout fix for DM page

---

client/components/Blog/header/Common.vue
client/components/Blog/shared/PostAuthor.vue
tests/components/Blog/header/__snapshots__/Blog.spec.js.snap
tests/components/Blog/header/__snapshots__/Common.spec.js.snap

1. Добавил прелоад параметр для картинок которые находятся в зоне видимости юзера. Предварительная загрузка картинок из видимой области позволяет улучшить метрику LCP в Page speed insight

MAR-1553 added preload link for images

---

server/radiator/index.js

Обновил конфигурацию радиатора

MAR-1575. Updated radiator config.

---

client/assets/styles/_vars.scss
client/components/OpenSource/Banner.vue
client/components/OpenSource/ParagraphSection.vue
client/components/shared/UIArrowButton.vue
client/data/boilerplatesList.js
client/data/openSourceTexts.js
client/pages/open-source.vue
tests/components/OpenSource/__snapshots__/Banner.spec.js.snap
tests/components/OpenSource/__snapshots__/ParagraphSection.spec.js.snap
tests/components/OpenSource/shared/__snapshots__/BoilerplatesList.spec.js.snap

1) Переделал секцию с текстом
2) Поправил воспроизведение анимаций
3) Поправил отступы
4) Поправил тексты

MAR-1400 Minor layout changes changes for Open Source page

---

client/api/blog.js
client/components/Ebook/Learn.vue
client/components/Ebook/Read.vue
client/components/Ebook/ReadCard.vue
client/pages/ebook.vue
client/store/modules/blog.js
tests/components/Ebook/Banner.spec.js
tests/components/Ebook/Learn.spec.js
tests/components/Ebook/LearnCard.spec.js
tests/components/Ebook/Read.spec.js
tests/components/Ebook/ReadCard.spec.js
tests/components/Ebook/__snapshots__/Banner.spec.js.snap
tests/components/Ebook/__snapshots__/Learn.spec.js.snap
tests/components/Ebook/__snapshots__/LearnCard.spec.js.snap
tests/components/Ebook/__snapshots__/Read.spec.js.snap
tests/components/Ebook/__snapshots__/ReadCard.spec.js.snap

1. Added markup for CU card on Ebook page
2. Added tests for CU card

MAR-1587 Added settings for CU posts

---

client/components/Blog/Main/AllPostsSection.vue
server/config/json/blog-redirects.json
server/config/json/hr-tags-redirects.json
server/config/json/invalid-links-redirects.json
tests/components/Blog/Main/AllPostsSection.spec.js
tests/components/Blog/Main/__snapshots__/AllPostsSection.spec.js.snap
tests/components/Blog/Main/__snapshots__/Main.spec.js.snap

1) Убрал категорию Job Opening из фильтра по постам
2) Добавил редиректы, которые перенаправляют на страницу - https://maddevs.io/careers/#open-positions со всех постов и страниц, которые относятся к Job Opening

MAR-1129 Removed the "Job Opening" category from blog, added the new redirects

---

client/components/core/CookieNotice.vue

* Добавил ссылку
* Поправил высоту

MAR-1569. Updated CookieNotice.

---

client/data/messengers.js
tests/components/core/Footer/__snapshots__/Footer.spec.js.snap
tests/components/core/Footer/__snapshots__/FooterContacts.spec.js.snap

* Обновил ссылку на messenger в футере

MAR-1570. Updated footer link.

---

client/components/Blog/Main/AllPostsSection.vue
package.json
server/config/json/hr-tags-redirects.json
tests/components/Blog/Main/AllPostsSection.spec.js
tests/components/Blog/Main/__snapshots__/AllPostsSection.spec.js.snap
tests/components/Blog/Main/__snapshots__/Main.spec.js.snap

1. поправил редиректы для постов
2. поправил команду для запуска юнит тестов
3. поправил вывод катгорий для фильтрации блог постов

MAR-1129 Corrected redirects for blog posts

---

README.md

* Обновил ридми
* Добавил много новой инфы о проекте

MAR-109. Updated a readme.

---

client/components/Blog/Main/BlogHeader.vue
client/components/Blog/shared/FeaturedPost.vue

Fixed color for texts in FeaturePost component

MAR-1644 added fixes fir blog styles

---

jest/configs/staging.config.js
jest/index.js
jest/utils/sendCoverageToSlack.js
package.json

* Changed format messages in test runner
* Added error handler errors in **sendMessageToSlack** func
* Updated npm script for run tests on staging

MAR-1644 returned func for send coverage to Slack

---

client/components/Blog/Main/BlogHeader.vue
client/components/DeliveryModels/Banner.vue

1) Немного поправил размеры текстов в первой, встречающей юзера секции ( Hero section ), чтобы они не отличались друг от друга. Поправил три места: Open-source, Delivery-models, Blog

MAR-1644 Corrected size of hero section on the Open Source, Delivery models and Blog pages

---

package-lock.json
package.json

MAR-1641. Updated radiator version.

---

client/components/Careers/Banner.vue
client/components/Careers/Benefits.vue
client/components/Careers/CTABanner.vue
tests/components/Careers/__snapshots__/Banner.spec.js.snap
tests/components/Careers/__snapshots__/CTABanner.spec.js.snap

MAR-1516 changes logic for btn in CTABanner

---

package-lock.json
package.json
server/radiator/index.js

1. Updated radiator version(added correct pagespeed calculating)
2. Updated config(activity graph periods)
https://maddevs.atlassian.net/browse/MAR-1670
https://maddevs.atlassian.net/browse/MAR-1671

MAR-1670. Updated radiator config.

---

client/components/Cases/peklo/BenefitsFromPekloTool.vue
client/components/Cases/peklo/ClusterisationAlgorithm.vue
client/components/Cases/peklo/PekloToolUnderTheHood.vue
tests/components/Cases/peklo/__snapshots__/BenefitsFromPekloTool.spec.js.snap
tests/components/Cases/peklo/__snapshots__/ClusterisationAlgorithm.spec.js.snap
tests/components/Cases/peklo/__snapshots__/PekloToolUnderTheHood.spec.js.snap

1. Update aos animation for Peklo case
2. Task: https://maddevs.atlassian.net/browse/MAR-550
3. Vlada`s feeback: https://maddevs.atlassian.net/browse/MAR-550?focusedCommentId=20897

MAR-1687 Update aos animation for Peklo case 

---

client/components/Blog/shared/LoadMoreButton.vue

1. update border radius and add hover effect for see more button, blog main page: https://maddevs.atlassian.net/browse/MAR-1371
Before: 
After:

MAR-1371 update styles for see more button

---

client/components/Careers/CTABanner.vue
tests/components/Careers/__snapshots__/CTABanner.spec.js.snap

MAR-1713 fixed links in CTA Banner on Careers page

---

client/featureFlags/config.js
client/pages/about-demo.vue

Создал по роуту https://maddevs.co/about-demo страницу для вывода и тестирования слайсов.

MAR-1543 Created the "about-page-demo"  route for slices testing

---

client/components/slices/ImageAttributesSlice.vue
tests/components/slices/__snapshots__/ImageAttributesSlice.spec.js.snap

* Removed width and height attributes from image
* Updated snapshots

MAR-1673. Fixed CTA banner in blog posts

---

client/data/caseYourcast.js
tests/components/Cases/yourcast/__snapshots__/Main.spec.js.snap
tests/components/Cases/yourcast/__snapshots__/Team.spec.js.snap
utils/getRoutes.js

1.  Update position for Chuck in Yourcast case: https://maddevs.atlassian.net/browse/MAR-1770
2.  Added new link in ignore list: https://maddevs.atlassian.net/browse/MAR-1680?focusedCommentId=21969

MAR-1770 update position for Chuck in Yourcast case 

---

package.json

MAR-1736 disable e2e test in CI

---

package-lock.json
package.json

* Updated radiator version from 1.5.0 to 1.6.0

MAR-1762. Updated radiator version.

---

client/components/Blog/Post/ContentLocker.vue
client/components/Blog/Post/Post.vue
client/components/Ebook/Read.vue
client/components/Ebook/ReadForm.vue
client/components/core/modals/ModalContentLocker.vue
tests/components/Blog/Post/ContentLocker.spec.js
tests/components/Blog/Post/__snapshots__/ContentLocker.spec.js.snap
tests/components/Blog/Post/__snapshots__/Post.spec.js.snap
tests/components/Ebook/__snapshots__/Read.spec.js.snap
tests/components/Ebook/__snapshots__/ReadForm.spec.js.snap
tests/components/core/modals/ModalContentLocker.spec.js
tests/components/core/modals/__snapshots__/ModalContentLocker.spec.js.snap
tests/components/core/modals/__snapshots__/ModalEbook.spec.js.snap

* Added content locker
* Updated styles of current Ebook modal
* Updated snapshots
* Added unit-tests for content locker and content locker modal
**Screenshots:**

MAR-1693. Added content locker for blogposts.

---

client/components/Blog/Post/ContentLocker.vue
client/components/Blog/Post/Post.vue
client/components/core/modals/ModalContentLocker.vue
tests/components/Blog/Post/__snapshots__/Post.spec.js.snap

* Fixed markup(image height)
* Added client-only
* Updated snapshots

MAR-1665. Fixed bugs with markup

---

client/components/Careers/shared/PositionForm.vue
client/components/core/Header/Header.vue
client/components/core/Modal.vue
client/components/core/forms/FooterForm.vue
client/components/core/modals/ModalSuccess.vue
client/components/core/modals/SuccessMessage.vue
tests/__snapshots__/successMessage.spec.js.snap
tests/components/Careers/shared/PositionForm.spec.js
tests/components/Careers/shared/__snapshots__/PositionForm.spec.js.snap
tests/components/core/Footer/__snapshots__/Footer.spec.js.snap
tests/components/core/Modal.spec.js
tests/components/core/forms/__snapshots__/FooterForm.spec.js.snap
tests/components/core/modals/ModalSuccess.spec.js
tests/components/core/modals/__snapshots__/ModalSuccess.spec.js.snap
tests/pages/ru/careers/__snapshots__/_uid.spec.js.snap

* Updated styles of SuccessModal
* Updated logic of SuccessModal
* Updated unit-tests

MAR-1787.  Huntflow response message feedback

---

client/components/core/Modal.vue
client/components/core/modals/ModalContentLocker.vue

MAR-1665. Updated modal styles.

---

client/components/Cases/yourcast/PhaseLiveStreamingTechnology.vue
client/data/caseYourcast.js
tests/components/Cases/yourcast/__snapshots__/PhaseLiveStreamingTechnology.spec.js.snap

1. Update posters 
2. Update video 
3. Task: https://maddevs.atlassian.net/browse/MAR-1681

MAR-1773 update posters and video in Yourcast case

---

client/components/shared/UIButton.vue
client/components/shared/UILinkButton.vue
client/components/shared/UIOutlinedButton.vue
client/prismicSlices/pageParts/ButtonSlice/index.vue
tests/components/shared/__snapshots__/UILinkButton.spec.js.snap
tests/components/shared/__snapshots__/UIOutlinedButton.spec.js.snap

Changed styles and props of:
- `client/components/shared/UIButton.vue`
- `client/components/shared/UILinkButton.vue`
- `client/components/shared/UIOutlinedButton.vue`

MAR-1818 Refactored styles and props of UI buttons

---

client/components/shared/UIButton.vue
client/components/shared/UILinkButton.vue
client/components/shared/UIOutlinedButton.vue
client/prismicSlices/pageParts/ButtonSlice/index.vue
client/prismicSlices/pageParts/StartScreen/index.vue

1) Changed the text size in the "StartScreen" slice
2) Changed props for the Button slice

MAR-1543 Minor changes for the  "StartScreen" slice and "Button" slice

---

client/api/ipInfo.js
client/components/Blog/Main/BlogHeader.vue
client/components/Blog/Post/Post.vue
client/components/Blog/header/Blog.vue
client/components/Blog/shared/FeaturedPost.vue
client/components/Blog/shared/PostCard.vue
client/components/Blog/shared/PostTag.vue
client/prismicSlices/pageParts/CardGridSlice/variations/RichTextCards.vue
tests/components/Blog/Main/__snapshots__/AllPostsSection.spec.js.snap
tests/components/Blog/Main/__snapshots__/AuthorPostsSection.spec.js.snap
tests/components/Blog/Main/__snapshots__/TagPostsSection.spec.js.snap
tests/components/Blog/Post/__snapshots__/Post.spec.js.snap
tests/components/Blog/shared/__snapshots__/PostCard.spec.js.snap

Links to tasks: 
https://maddevs.atlassian.net/browse/MAR-860,
https://maddevs.atlassian.net/browse/MAR-1814
1. Fixed styles (colors & positions) in components
2. Refactored function to get info from user from two APIs

MAR-1814 Changed function to get IP info and styles in components

---

client/components/Blog/header/Blog.vue
client/components/Blog/shared/FeaturedPost.vue

Link to the task: https://maddevs.atlassian.net/browse/MAR-1904
1. Added style to FeaturedPost to make the blocks pressed to the top
2. Added style to Blog to align the blocks horizontally

MAR-1904. Fixed styles in components Blog & FeaturedPost

---

client/components/Ebook/ReadForm.vue

Link to task: https://maddevs.atlassian.net/browse/MAR-1948
Changed email and url to the current page

MAR-1948. Changed email and href to the page

---

client/components/Blog/Post/Post.vue
client/featureFlags/config.js
tests/components/Blog/Post/__snapshots__/Post.spec.js.snap

Added feature flag to Disqus component

MAR-350. Added feature flag for disqus component

---

client/components/Blog/Main/TagBanner.vue
client/pages/blog/search-result/index.vue
client/pages/customer-university/index.vue
tests/components/Blog/Main/TagBanner.spec.js
tests/components/Blog/Main/__snapshots__/TagBanner.spec.js.snap
tests/pages/blog/tag/_uid/__snapshots__/index.spec.js.snap
utils/getRoutes.js

1. Added index page for CU posts

MAR-1009 added page for CU

---

client/components/Cases/CasesList.vue
client/components/DeliveryModels/Banner.vue
client/pages/case-studies/index.vue

1. Added preload for video in first card, case studies page
2. Update img path for Banner, DM page
3. Remove test preload link in case studies index component
3. Task: https://maddevs.atlassian.net/browse/MAR-1059

MAR-1977 Delivery Models and Case studies page optimization

---

client/prismicSlices/pageParts/CustomerLogoSlice/index.vue
tests/prismicSlices/pageParts/CustomerLogoSlice/__snapshots__/index.spec.js.snap
tests/prismicSlices/pageParts/CustomerLogoSlice/index.spec.js

1) Task: https://maddevs.atlassian.net/browse/MAR-1804
2) Added new tests for CustomerLogoSlice
3) Test result :

MAR-1804. Added new tests for CustomerLogoSlice

---

client/components/About/CustomerTestimonials.vue
client/prismicSlices/pageParts/CustomerTestimonials/index.vue
tests/components/About/CustomerTestimonials.spec.js
tests/components/About/__snapshots__/CustomerTestimonials.spec.js.snap
tests/components/Ebook/Read.spec.js
tests/components/core/modals/ModalEbook.spec.js
tests/prismicSlices/pageParts/CustomerTestimonials/__snapshots__/index.spec.js.snap
tests/prismicSlices/pageParts/CustomerTestimonials/index.spec.js

1) Task: https://maddevs.atlassian.net/browse/MAR-1806
2) Added new tests for  CustomerTestimonialsSlice 
3) Test results:

MAR-1806. Added a test for CustomerTestimonialsSlice

---

client/api/ipInfo.js
nuxt.config.js
tests/api/ipInfo.spec.js

Link to the task: https://maddevs.atlassian.net/browse/MAR-2014
Changed function to get ip, city, country from user
Updated tests and screenshots
API used: https://ipinfo.io/
Expected result:

MAR-2014. Changed function to get an info from user

---

client/components/Blog/Post/Post.vue
client/featureFlags/config.js
tests/components/Blog/Post/__snapshots__/Post.spec.js.snap

Link to the task: **https://maddevs.atlassian.net/browse/MAR-350**
Deleted feature flags for Disqus to deploy to production

MAR-350. Deleted feature flags for Disqus

---

client/components/Cases/citycam/ChallengesAndSolutions.vue
client/components/Cases/citycam/DevicePerfecting.vue
client/components/Cases/citycam/PowerSupply.vue
client/components/Cases/citycam/Prototype.vue
tests/components/Cases/citycam/__snapshots__/ChallengesAndSolutions.spec.js.snap
tests/components/Cases/citycam/__snapshots__/DevicePerfecting.spec.js.snap
tests/components/Cases/citycam/__snapshots__/PowerSupply.spec.js.snap
tests/components/Cases/citycam/__snapshots__/Prototype.spec.js.snap

**Task:**
https://maddevs.atlassian.net/browse/MAR-2008
**Done:**
Adjusted spacing in the sections per changes made in figma.
**To do:**
Might post more changes upon John's review

MAR-2008 Changed associated with feedback on Mic. case 

---

client/data/casesList.js
tests/components/Cases/__snapshots__/CasesList.spec.js.snap

Changed sub-title of case card to IoT

MAR-2006 changed subtitle of case card to IoT

---

client/data/casesList.js
tests/components/Cases/__snapshots__/CasesList.spec.js.snap
tests/components/Cases/__snapshots__/SJMCVideo.spec.js.snap
tests/pages/case-studies/__snapshots__/index.spec.js.snap

task: https://maddevs.atlassian.net/browse/MAR-2055

Mar 2055 убрал карточку кейса до вывода в прод

---

client/components/Ebook/Read.vue
package-lock.json
tests/components/Ebook/Read.spec.js
tests/components/Ebook/__snapshots__/Read.spec.js.snap

Added filter by "Pricing strategies" tag for CU posts on the `insights/ebooks/pricing-strategies/` page

MAR-2059 Filtered the pricing strategies CU posts

---

client/components/Cases/citycam/DevicePerfecting.vue
tests/components/Cases/citycam/__snapshots__/DevicePerfecting.spec.js.snap

Adjusted slider margin in DevicePerfecting.

MAR-2066 adjusted margin of slider in DevicePerfecting.vue of CityCam case

---

client/components/Cases/CasesList.vue
client/featureFlags/config.js
client/pages/case-studies/citycam.vue
tests/pages/case-studies/__snapshots__/citycam.spec.js.snap

Task: https://maddevs.atlassian.net/browse/MAR-2064
Removed feature flags in cityCam page and caseList

MAR-2064 removed feature flags from citycam case

---

client/api/blog.js
client/components/Blog/shared/CustomerUniversityListItem.vue
client/store/index.js
client/store/modules/customerUniversitySection.js
tests/components/Blog/shared/__snapshots__/CustomerUniversityListItem.spec.js.snap

1) https://maddevs.atlassian.net/browse/MAR-1927
2) Created Vuex module for getting customer university section posts

MAR-2032 Created Vuex module for getting customer university section posts

---

client/components/core/HeaderV2/HeaderMenu.vue
client/components/core/HeaderV2/HeaderMobile/HeaderMobileContacts.vue
client/components/core/HeaderV2/HeaderMobile/HeaderMobileMenu.vue
client/components/core/HeaderV2/HeaderMobile/HeaderMobileNavigation.vue
client/components/core/HeaderV2/HeaderMobile/HeaderMobileSection.vue
client/components/core/HeaderV2/HeaderMobile/HeaderMobileSocials.vue
client/components/core/HeaderV2/HeaderMobile/index.vue
client/components/core/HeaderV2/HeaderNavigation.vue
client/components/core/HeaderV2/HeaderPost.vue
client/components/core/HeaderV2/HeaderSection.vue
client/components/core/HeaderV2/index.vue
client/helpers/extractMenuLink.js
jest/configs/coverageThreshold.config.js

1) Refactored code and styles in the `components/core/HeaderV2` folder
2) Added the HeaderMobile components to `components/core/HeaderV2` folder

MAR-2065 Created the HeaderMobile component for HeaderV2

---

client/components/Blog/Main/NewCustomerUniversitySection.vue
client/components/Blog/shared/CustomerUniversityButton.vue
client/components/Blog/shared/CustomerUniversityCard.vue
client/components/Blog/shared/CustomerUniversityTextCard.vue
tests/components/Blog/Main/__snapshots__/NewCustomerUniversitySection.spec.js.snap
tests/components/Blog/shared/__snapshots__/CustomerUniversityCard.spec.js.snap

1) https://maddevs.atlassian.net/browse/MAR-1927
2) Сorrected the styles and refactored the customer university section

MAR-2083 Сorrected the styles and refactored the customer university section

---

client/components/core/HeaderV2/HeaderNavigation.vue
client/components/core/HeaderV2/HeaderSection.vue
client/components/core/HeaderV2/index.vue
client/store/modules/header.js

1.  Changed logic for HeaderLogo
2. Changed styles on mob screens for header content
3. Added link for main links in menu

MAR-2084 fixes for New Header

---

client/components/slices/AuthorSlice.vue
tests/unit/components/slices/__snapshots__/AuthorSlice.spec.js.snap

1. Added link to author page for author info in post bottom line

MAR-2082 Added link for Auton in Blog post bottom line

---

client/components/Blog/Main/NewCustomerUniversitySection.vue
client/components/Blog/shared/CustomerUniversityButton.vue
client/components/Blog/shared/CustomerUniversityCard.vue
client/components/Blog/shared/CustomerUniversityTextCard.vue
client/components/Blog/shared/СustomerUniversityTitle.vue

1) https://maddevs.atlassian.net/browse/MAR-1927
2) Changed the size and margins of texts

MAR-2109 Changed the size and margins of texts

---

client/components/Cases/godee/ParallaxImage.vue
client/components/Cases/shared/CaseHeader.vue
client/components/shared/UIBeforeAfterImage.vue
tests/unit/components/Cases/godee/ParallaxImage.spec.js
tests/unit/components/Cases/godee/__snapshots__/BeforeAfter.spec.js.snap
tests/unit/components/Cases/godee/__snapshots__/Main.spec.js.snap
tests/unit/components/Cases/godee/__snapshots__/ParallaxImage.spec.js.snap
tests/unit/components/Cases/shared/__snapshots__/CaseHeader.spec.js.snap
tests/unit/components/shared/__snapshots__/UIBeforeAfterImage.spec.js.snap
tests/unit/pages/case-studies/__snapshots__/citycam.spec.js.snap

1) https://maddevs.atlassian.net/browse/MAR-603
2) Change the method of connecting images from background image to img and added lazy loading
3) Updated test and snapshots

MAR-667 Change the method of connecting images from background image to img and added lazy loading

---

client/prismicSlices/pageParts/StartScreen/index.vue

Task: https://maddevs.atlassian.net/browse/MAR-2127

MAR-2127 fixed text size of header in About page

---

client/components/core/HeaderV2/HeaderMenu.vue
client/components/core/HeaderV2/HeaderMobile/HeaderMobileMenu.vue
client/components/core/HeaderV2/HeaderNavigation.vue
client/components/core/HeaderV2/HeaderPost.vue
client/components/core/HeaderV2/HeaderSection.vue

1. Fixed height for new header on screens 13
2. Removed empty links in header drop down
3. Fixed border bottom for Post in new header

MAR-2084 fixed bugs for new Header

---

client/assets/styles/cases/_grid.scss
client/components/Cases/clutch/About.vue
client/components/Cases/shared/StatisticsCard.vue
client/components/Cases/shared/StatisticsContainer.vue
client/data/clutch.js
tests/unit/components/Cases/shared/__snapshots__/StatisticsContainer.spec.js.snap
tests/unit/components/Cases/veeqo/__snapshots__/About.spec.js.snap
tests/unit/components/Cases/veeqo/__snapshots__/Main.spec.js.snap

Task: https://maddevs.atlassian.net/browse/MAR-2092
Done:
Added About section. 
Added shared StatisticsCard.vue
Modified shared StatisticsContainer.vue section from flex to grid
Updated snapshots

MAR-2092 - added About section and shared StatisticsCard.vue

---

client/components/Blog/Main/NewCustomerUniversitySection.vue
client/components/Blog/shared/CustomerUniversityButton.vue
client/components/Blog/shared/CustomerUniversityCard.vue
client/components/Blog/shared/CustomerUniversityTextCard.vue
client/components/Blog/shared/СustomerUniversityTitle.vue
tests/unit/components/Blog/shared/__snapshots__/CustomerUniversityCard.spec.js.snap

1) https://maddevs.atlassian.net/browse/MAR-1927
2) Сorrected the margins 
3) Refactored the customer university card
4)

MAR-2109 Сorrected the margins and refactored the customer university card

---

client/components/Cases/godee/Main.vue
tests/unit/components/Cases/godee/__snapshots__/Main.spec.js.snap

1) https://maddevs.atlassian.net/browse/MAR-603
2) Added lazy loading for iframe

MAR-603 Added lazy loading for iframe

---

client/assets/styles/cases/_grid.scss
client/components/Cases/clutch/Main.vue
client/components/Cases/clutch/TechChallenges.vue
client/components/Cases/clutch/WhyClutch.vue
client/data/clutchCase.js
tests/unit/components/Cases/clutch/TechChallenges.spec.js
tests/unit/components/Cases/clutch/WhyClutch.spec.js
tests/unit/components/Cases/clutch/__snapshots__/TechChallenges.spec.js.snap
tests/unit/components/Cases/clutch/__snapshots__/WhyClutch.spec.js.snap

Task: https://maddevs.atlassian.net/browse/MAR-2093
https://maddevs.atlassian.net/browse/MAR-2094
Prepared the About section and its test
Prepared the TechChallenges section and its test

Mar-2093 about section of clutch case

---

client/components/Cases/godee/ParallaxImage.vue

1) https://maddevs.atlassian.net/browse/MAR-603
2) Corrected the adaptive parallax of the image

MAR-603 Corrected the adaptive parallax of the image

---

client/components/Cases/clutch/Standup.vue
tests/unit/components/Cases/clutch/Standup.spec.js
tests/unit/components/Cases/clutch/__snapshots__/Standup.spec.js.snap

Task: https://maddevs.atlassian.net/browse/MAR-2103
Done: Added Standup section and its test

MAR-2103 added Standup section of Clutch case

---

client/prismicSlices/pageParts/VideoSlice/index.vue

The link to the task: https://maddevs.atlassian.net/browse/MAR-2139
Deleted margin from h2 title

MAR-2139. Deleted margin in title

---

client/prismicSlices/pageParts/StartScreen/index.vue

1. Added style for small class

MAR-2139. Added styles for small class

---

client/prismicSlices/pageParts/StartScreen/index.vue

Changed line-height for 768px size

MAR-2139. Changed line-height for 768px

---

README.md
jsconfig.json

The link to the task: https://maddevs.atlassian.net/browse/MAR-1782
1. Added text and link to the documentation of BEM

MAR-1782. Added text of BEM

---

client/components/core/Modal.vue

task: https://maddevs.atlassian.net/browse/MAR-2156
Done: modified modal height in respect to modal header height

MAR-2156 modified modal height in respect to modal header height

---

client/components/Cases/clutch/DevOps.vue
client/components/Cases/clutch/Pipelines.vue
client/components/Cases/clutch/Standup.vue
client/components/Cases/clutch/WhyClutch.vue
client/components/Cases/clutch/WidgetSpeed.vue
client/components/Cases/clutch/Workflow.vue
client/helpers/countDown.js
tests/unit/components/Cases/clutch/__snapshots__/DevOps.spec.js.snap
tests/unit/components/Cases/clutch/__snapshots__/Pipelines.spec.js.snap
tests/unit/components/Cases/clutch/__snapshots__/Standup.spec.js.snap
tests/unit/components/Cases/clutch/__snapshots__/WhyClutch.spec.js.snap
tests/unit/components/Cases/clutch/__snapshots__/WidgetSpeed.spec.js.snap

Task: https://maddevs.atlassian.net/browse/MAR-2107
Done:
1. Why do top firms & decision makers trust Clutch? - changed color of list item text to white explicitly
2. Website speed boost - increased time of countup to 5 sec.
3. Widget speed optimisation - uploaded better pics to AWS
4. Implemented Ad Service - changed source of images for correct lazy loading
Development workflow - adjusted width of banner on widers screens
Pipelines and testing - changed lottie animation setting
Automated daily standups - uploaded better image to AWS removed safari frame, since new pic comes with frame.

MAR-2107 minor adjustments of clutch case

---

package-lock.json
package.json

1) https://maddevs.atlassian.net/browse/MAR-2078
2) Updated the radiator version

MAR-2157 updated the radiator version

---

client/components/Cases/clutch/DataAndPasswords.vue
client/components/Cases/clutch/Standup.vue
client/components/Cases/clutch/WidgetSpeed.vue

Task: https://maddevs.atlassian.net/browse/MAR-2158
Done: changed table text weight to normal in CLutch case

MAR-2158 changed table text weight to normal in CLutch case

---

client/prismicSlices/pageParts/ProgressSlice/index.vue
tests/unit/prismicSlices/pageParts/ProgressSlice/__snapshots__/index.spec.js.snap

Task: Icons are not loaded
Done: updated img scr in progress slice

MAR-2148 updated img scr in progress slice

---

client/components/Ebook/ReadForm.vue

Link to the task: https://maddevs.atlassian.net/browse/MAR-2170
Added new field called fromSender, for get email from user

MAR-2170. Changed email for marketing

---

client/components/Cases/clutch/DevOps.vue
client/components/Cases/clutch/OutStuffing.vue
client/components/Cases/clutch/Pipelines.vue
client/components/Cases/clutch/Standup.vue
client/components/Cases/clutch/WidgetSpeed.vue
client/components/Cases/clutch/Workflow.vue
client/helpers/countDown.js
tests/unit/components/Cases/clutch/__snapshots__/DevOps.spec.js.snap
tests/unit/components/Cases/clutch/__snapshots__/OutStuffing.spec.js.snap
tests/unit/components/Cases/clutch/__snapshots__/Standup.spec.js.snap
tests/unit/components/Cases/clutch/__snapshots__/Workflow.spec.js.snap

Task: https://maddevs.atlassian.net/browse/MAR-2169
Done: changed Ad banner in devOps section. 
Refactored and fixed sections per feedback

Mar-2169 adjusted Ad block in Clutch case

---

client/components/Cases/shared/StatisticsCard.vue
client/data/casesList.js
client/data/seo.js
tests/unit/components/Cases/__snapshots__/CasesList.spec.js.snap
tests/unit/components/Cases/clutch/About.spec.js
tests/unit/components/Cases/clutch/__snapshots__/About.spec.js.snap
tests/unit/components/Cases/clutch/__snapshots__/DataAndPasswords.spec.js.snap
tests/unit/components/Cases/shared/StatisticsCard.spec.js
tests/unit/components/Cases/shared/__snapshots__/StatisticsCard.spec.js.snap
tests/unit/pages/case-studies/__snapshots__/clutch.spec.js.snap
tests/unit/pages/case-studies/clutch.spec.js

Task: https://maddevs.atlassian.net/browse/MAR-2113
Done:Added test for clutch page, About, StatisticsCard. Updated DataAndPasswords CaseList snapshots

MAR-2113 Covered Clutch case with unit tests

---

client/components/Cases/clutch/Standup.vue

Changed padding of table header in Standups on mobile devices

MAR-2150 changed padding of table header in Standups on mobile devices

---

client/components/Blog/Main/NewCustomerUniversitySection.vue
tests/unit/components/Blog/Main/__snapshots__/NewCustomerUniversitySection.spec.js.snap

Link to the task: https://maddevs.atlassian.net/browse/MAR-2202
1. Added computed property
2. Updated test snapshots

MAR-2202. Added computed property & updated snapshots

---

client/components/Careers/shared/PositionForm.vue
client/pages/faq.vue
server/services/EmailsService.js
tests/unit/components/Careers/shared/PositionForm.spec.js

Link to the task: https://maddevs.atlassian.net/browse/MAR-2024
1. Added conditional operator

MAR-2024. Added conditional operator

---

client/prismicSlices/pageParts/ButtonSlice/index.vue

Link to the task: https://maddevs.atlassian.net/browse/MAR-2187
1. Changed styles for button slice to adaptive

MAR-2187. Changed styles for buttons

---

client/components/Cases/clutch/DevOps.vue
tests/unit/components/Cases/clutch/__snapshots__/DevOps.spec.js.snap

task: https://maddevs.atlassian.net/browse/MAR-2216
repositioned logo in Ad banner of DevOps section

MAR-2216 repositioned logo in Ad banner of DevOps section

---

package-lock.json
package.json
server/radiator/index.js

1) https://maddevs.atlassian.net/browse/MAR-1719
2) Updated Radiator
2) Updated Radiator config

MAR-1719 Updated Radiator. Updated Radiator config

---

server/radiator/index.js

1) https://maddevs.atlassian.net/browse/MAR-1719
2) Updated Radiator config

MAR-1719 Updated Radiator config

---

client/mixins/buildBlogPostMixin.js
client/pages/about/careers/_uid.vue

Task: https://maddevs.atlassian.net/browse/MAR-2193
Done:  fixed canonical links in header blog -> insights/blog & about -> ru/about

MAR-2193  fixed canonical links in header blog 

---

router.config.js

1) https://maddevs.atlassian.net/browse/MAR-2147
2) Deleted the feature flags test data

MAR-2261 Deleted the feature flags test data

---

server/config/json/invalid-links-redirects.json

Task: https://maddevs.atlassian.net/browse/MAR-2267

MAR-2267 modified redirect from /open-source

---

client/components/Cases/CasesListItem.vue

Task: https://maddevs.atlassian.net/browse/MAR-2296
Added playsinline prop for video for IOS devices

MAR-2296 added playsinline for IOS devices

---

package-lock.json
package.json

1) https://maddevs.atlassian.net/browse/MAR-1762
2) Updated Radiator version

MAR-1762 Updated Radiator version

---

.slicemachine/assets/client/prismicSlices/pageParts/BenefitSlice/index.stories.js
.slicemachine/assets/client/prismicSlices/pageParts/BenefitSlice/mocks.json
.slicemachine/mock-config.json
client/prismicSlices/pageParts/BenefitSlice/index.vue
client/prismicSlices/pageParts/BenefitSlice/model.json
client/prismicSlices/pageParts/GridLottieSlice/variations/GridLottieLink.vue
tests/unit/prismicSlices/pageParts/BenefitSlice/__snapshots__/index.spec.js.snap
tests/unit/prismicSlices/pageParts/BenefitSlice/index.spec.js

Task: https://maddevs.atlassian.net/browse/MAR-2270
Done: added condition to display Lottie in the slice, added benefit slice

MAR-2270 added condition per presence of lottie in lottie slice

---

server/radiator/index.js

1) Updated weekly radiator config

MAR-1768 Updated weekly radiator config

---

tests/unit/pages/approach/delivery-models/__snapshots__/index.spec.js.snap
tests/unit/pages/approach/delivery-models/index.spec.js

the task: https://maddevs.atlassian.net/browse/MAR-2420
1. Created test for the delivery models component

MAR-2420. Created test for the Delivery-models

---

client/components/Cases/BuildDevTeam.vue
client/components/DeliveryModels/CTABanner.vue
tests/unit/components/Cases/__snapshots__/BuildDevTeam.spec.js.snap

Task: https://maddevs.atlassian.net/browse/MAR-2449

MAR-2449 Updated CTA banners for delivery-models and case-studies pages

---

tests/unit/components/Careers/shared/PositionLabels.spec.js
tests/unit/components/Careers/shared/PositionTags.spec.js
tests/unit/components/Careers/shared/UnderlinedButton.spec.js
tests/unit/components/Careers/shared/__snapshots__/PositionLabels.spec.js.snap
tests/unit/components/Careers/shared/__snapshots__/PositionTags.spec.js.snap
tests/unit/components/shared/UICustomersList.spec.js
tests/unit/components/shared/__snapshots__/UICustomersList.spec.js.snap

1) https://maddevs.atlassian.net/browse/MAR-2345
2) updated tests for careers shared components

MAR-2345 updated tests for careers shared components

---

tests/unit/components/OpenSource/shared/BoilerplatesList.spec.js
tests/unit/components/OpenSource/shared/BoilerplatesListItem.spec.js
tests/unit/components/OpenSource/shared/FeaturedProjectsListItem.spec.js
tests/unit/components/OpenSource/shared/TitleDesc.spec.js
tests/unit/components/OpenSource/shared/__snapshots__/BoilerplatesListItem.spec.js.snap
tests/unit/components/OpenSource/shared/__snapshots__/FeaturedProjectsListItem.spec.js.snap
tests/unit/components/OpenSource/shared/__snapshots__/TitleDesc.spec.js.snap

1) https://maddevs.atlassian.net/browse/MAR-2340
2) Added test for TitleDesc component

MAR-2343 Added test for TitleDesc component

---

client/plugins/link-resolver.js

The task: https://maddevs.atlassian.net/browse/MAR-2446
1. Added conditional operator to handle customer-university link

MAR-2446. Added conditional operator to handle customer-university link

---

tests/unit/components/shared/LottieMad.spec.js
tests/unit/components/shared/__snapshots__/LottieMad.spec.js.snap

Task: https://maddevs.atlassian.net/browse/MAR-2423
Done: covered lottie mad with test

MAR-2423 Unit test for lottie mad

---

jest/configs/base.config.js

1) https://maddevs.atlassian.net/browse/MAR-2342
2) Added radiator configuration to ignore for tests

MAR-2341 Added radiator configuration to ignore for tests

---

tests/unit/components/slices/Careers/VacancyText.spec.js
tests/unit/components/slices/Careers/__snapshots__/VacancyText.spec.js.snap

1) https://maddevs.atlassian.net/browse/MAR-2341
2) Updated VacancyText component test

MAR-2341 Updated VacancyText component test

---

client/prismicSlices/pageParts/BenefitSlice/index.vue
tests/unit/prismicSlices/pageParts/BenefitSlice/__snapshots__/index.spec.js.snap

Task: https://maddevs.atlassian.net/browse/MAR-2467
Done: adjusted css for icons, set icon container width and height, updated snapshot.

MAR-2467 Modified icon css in benefit slice

---

package-lock.json
package.json
server/radiator/index.js

1) https://maddevs.atlassian.net/browse/MAR-1768
2) Updated Radiator version
3) Corrected lighthouse config

MAR-1768 Updated Radiator version

---

client/components/core/Modal.vue
client/components/core/forms/BaseForm.vue
client/components/core/forms/ContactMeForm.vue
client/components/core/forms/RadioButtons.vue
tests/unit/components/core/forms/ContactMeForm.spec.js
tests/unit/components/core/forms/__snapshots__/ContactMeForm.spec.js.snap
tests/unit/components/core/forms/__snapshots__/FooterForm.spec.js.snap
tests/unit/components/core/modals/__snapshots__/RadioButtons.spec.js.snap

Task: https://maddevs.atlassian.net/browse/MAR-2465
Done: updated contact me form, got rid of the default choice, changed modal height, updated test and snapshots.

MAR-2465 updated ContactMeForm and snapshots

---

.slicemachine/assets/client/prismicSlices/pageParts/CtaBannerSlice/index.stories.js
.slicemachine/assets/client/prismicSlices/pageParts/CtaBannerSlice/mocks.json
client/prismicSlices/pageParts/BenefitSlice/index.vue
client/prismicSlices/pageParts/CtaBannerSlice/components/CTAModal.vue
client/prismicSlices/pageParts/CtaBannerSlice/index.vue
client/prismicSlices/pageParts/CtaBannerSlice/model.json
client/prismicSlices/pageParts/NavLinkSlice/index.vue
tests/unit/prismicSlices/pageParts/CTABannerSlice/__snapshots__/index.spec.js.snap
tests/unit/prismicSlices/pageParts/CTABannerSlice/index.spec.js

1. Added the ability to select a modal window for the cta banner
2. Changed unit-tests

MAR-2448 Updated logic of modal windows in the CtaBannerSlice component

---

client/components/Cases/BuildDevTeam.vue
client/components/DeliveryModels/CTABanner.vue
client/components/core/HeaderV2/index.vue
client/components/core/modals/ModalContactMe.vue
client/prismicSlices/pageParts/CtaBannerSlice/components/CTAModal.vue
tests/unit/components/DeliveryModels/__snapshots__/CTABanner.spec.js.snap
tests/unit/components/core/HeaderV2/__snapshots__/index.spec.js.snap

1) https://maddevs.atlassian.net/browse/MAR-2479
2) Changed the id in contact me modals

MAR-2479 Changed the id in contact me modals

---

client/components/core/modals/ModalContentLocker.vue
client/components/core/modals/ModalEbook.vue

Task: https://maddevs.atlassian.net/browse/MAR-2502
Done: fixed modal ebook height

MAR-2502 fixed modal ebook height

---

client/components/Cases/nambataxi/Benefits.vue
client/components/Cases/nambataxi/MobileApplications.vue
client/components/Cases/nambataxi/Requirements.vue
client/data/caseNambaTaxi.js

Task: https://maddevs.atlassian.net/browse/MAR-2501
Done: modified positions, cards spacing and scroll speed in Namba case

MAR-2501 modified positions, cards spacing and scroll speed

---

server/controllers/CareersController.js
server/controllers/tests/CareersController.test.js
server/services/IPService.js
tests/unit/plugins/get-media-from-s3.spec.js
tests/unit/prismicSlices/pageParts/TeamCards/index.spec.js

the task: https://maddevs.atlassian.net/browse/MAR-2504
1. Changed variables in the body

MAR-2504. Fixed problems with data from sendpulse

---

package-lock.json
package.json
server/radiator/index.js

1) https://maddevs.atlassian.net/browse/MAR-2328
2) Updated radiator version and configs

MAR-2328 Updated radiator version and configs

---

client/prismicSlices/pageParts/TechnologiesAndTools/components/ToolsCategories.vue
client/prismicSlices/pageParts/TechnologiesAndTools/variations/ExistingToolsGrid.vue

- Fixed problems with data extract
- Minor layout fixes

MAR-2447 Fixed errors of ExistingToolsSlice component 

---

client/prismicSlices/pageParts/TeamCards/index.vue

Fixed problems with repeating animation

MAR-2272. Fixed problems with repeating animation

---

client/components/Ebook/Banner.vue
client/components/core/Modal.vue
client/components/core/modals/ModalContentLocker.vue
client/components/core/modals/ModalEbook.vue
client/components/core/modals/SuccessMessage.vue
tests/unit/components/Ebook/__snapshots__/Banner.spec.js.snap
tests/unit/components/core/modals/__snapshots__/ModalContentLocker.spec.js.snap
tests/unit/components/core/modals/__snapshots__/SuccessMessage.spec.js.snap

1) https://maddevs.atlassian.net/browse/MAR-2517
2) https://maddevs.atlassian.net/browse/MAR-2518
3) Removed id duplicate in the modal
4) Replace the id in the ebook modal

MAR-2517 Removed id duplicate in the modal

---

client/pages/insights/blog/_uid.vue
tests/unit/pages/blog/__snapshots__/_uid.spec.js.snap

1) https://maddevs.atlassian.net/browse/MAR-2547
2) Fixed sharing post on linkedin

MAR-2547 Fixed sharing post on linkedin

---

client/prismicSlices/pageParts/GridLottieSlice/variations/GridLottieLink.vue

the task: https://maddevs.atlassian.net/browse/MAR-2499
1. Added the conditional operator to the arrow button component

MAR-2499. Added the conditional operator to the arrow button component

---

server/radiator/index.js

1) https://maddevs.atlassian.net/browse/MAR-2592
2) Hid the charts in the weekly radiator

MAR-2592 Hid the charts in the weekly radiator

---

.eslintrc
client/helpers/localStorage.js
tests/unit/helpers/countDown.spec.js
tests/unit/helpers/localStorage.spec.js
tests/unit/helpers/textEllipsis.spec.js

1) https://maddevs.atlassian.net/browse/MAR-2457
2) Added new tests for helper functions

MAR-2457 Added new tests for helper functions

---

client/data/seo.js

the task: https://maddevs.atlassian.net/browse/MAR-2195
1. Added a conditional operator to the jsonLd

MAR-2195. Added a conditional operator to the jsonLd

---

client/assets/styles/_global.scss
client/components/Careers/shared/PositionForm.vue
server/controllers/CareersController.js
server/controllers/tests/CareersController.test.js
tests/unit/components/Careers/shared/PositionForm.spec.js

the task: https://maddevs.atlassian.net/browse/MAR-2612
1. Added the recaptcha to the PositionForm component
2. Updated tests
3. Added logic to the backend side for handle the recaptcha token
4. Added global styles to hide the recaptcha

MAR-2283. Added the recaptcha to the PositionForm && updated tests

---

client/data/caseGodee.js
client/data/caseSJMC.js
tests/unit/components/Cases/godee/__snapshots__/Main.spec.js.snap
tests/unit/components/Cases/godee/__snapshots__/Team.spec.js.snap

Task - https://maddevs.atlassian.net/browse/MAR-2619 
link to page - http://192.168.2.106:3000/clients/case-studies/godee/
Сhanged the list of staff positions on the goodee and on the SJMC case studies 
before - https://i.imgur.com/2SdFfXs.png  
after - https://i.imgur.com/I0bxR2q.png
+ 
before - https://i.imgur.com/TrjxOnC.png
after - https://i.imgur.com/KyqYJsP.png

Edited team positions on GoDee page

---

README.md

the task: https://maddevs.atlassian.net/browse/MAR-2573
1. Updated README.md file

MAR-2573. Updated README.md file

---

client/components/Ebook/ReadForm.vue
client/components/core/forms/BaseForm.vue
client/components/core/forms/ContactMeForm.vue
client/components/core/forms/FooterForm.vue
client/components/core/forms/OrderProjectFromUsForm.vue
tests/unit/components/Ebook/__snapshots__/ReadForm.spec.js.snap
tests/unit/components/core/Footer/__snapshots__/Footer.spec.js.snap
tests/unit/components/core/forms/__snapshots__/ContactMeForm.spec.js.snap
tests/unit/components/core/forms/__snapshots__/FooterForm.spec.js.snap
tests/unit/components/core/forms/__snapshots__/GetExpertAdviceForm.spec.js.snap
tests/unit/components/core/forms/__snapshots__/GetYourTrustedItPartnerForm.spec.js.snap
tests/unit/components/core/forms/__snapshots__/IndividualsForm.spec.js.snap
tests/unit/components/core/forms/__snapshots__/InfrastructureAuditForm.spec.js.snap
tests/unit/components/core/forms/__snapshots__/OrderProjectFromUsForm.spec.js.snap
tests/unit/components/core/forms/__snapshots__/TeamsForm.spec.js.snap

task: https://maddevs.atlassian.net/jira/software/c/projects/MAR/boards/47?modal=detail&selectedIssue=MAR-2599&assignee=61acf073977c5b0072556985 
description: added id to form buttons for GA 
-Contact me form 
-Order a project now form 
-Submit your project form
-Download Ebook from
example: 
tests:

MAR-2599. Added id to form buttons for GA

---

client/plugins/sentry.js

1. https://maddevs.atlassian.net/browse/MAR-2634
2. Added new ignore errors and deny urls for sentry. Reduced traces sample rate.

MAR-2634 Sentry minor fixes

---

client/plugins/google-tag-manager-debug.js
nuxt.config.js

1. https://maddevs.atlassian.net/browse/MAR-2228
2. Fix GTM config. Enable debug for GTM

MAR-2228 Google tag manager fix

---

server/config/index.js
server/radiator/index.js

1. https://maddevs.atlassian.net/browse/MAR-2650
2. Reduced tracesSampleRate for backend and radiator

MAR-2650 Fix Sentry Transactions

---

client/components/Ebook/ReadForm.vue
tests/unit/components/Ebook/__snapshots__/ReadForm.spec.js.snap

task:
https://maddevs.atlassian.net/jira/software/c/projects/MAR/boards/47?modal=detail&selectedIssue=MAR-2599&assignee=61acf073977c5b0072556985 
description: 
deleted boolean value from form

MAR-2599. fix bug. deleted debug code from form.

---

server/index.js
server/radiator/index.js

1) https://maddevs.atlassian.net/browse/MAR-2658
2) Divided the radiator into staging and production

MAR-2658 Divided the radiator into staging and production

---

client/prismicSlices/pageParts/CtaBannerSlice/index.vue

1. Changed max-width of the description

MAR-2643. Changed max-width of the description

---

client/components/Cases/nambafood/InfrastructureSchema.vue

The task: https://maddevs.atlassian.net/browse/MAR-2621
1. Changed an animation name on the page maddevs.io/clients/case-studies/namba-food/

MAR-2621. Changed an animation name

---

utils/getRoutes.js

> [MAR-2677](https://maddevs.atlassian.net/browse/MAR-2677)
Getting custom pages only from production

MAR-2677 Fix bad links in sitemap

---

client/components/Blog/Main/NewCustomerUniversitySection.vue
client/components/core/banners/MadCommunityBanner.vue
tests/unit/components/Blog/Main/__snapshots__/NewCustomerUniversitySection.spec.js.snap

task: 
https://maddevs.atlassian.net/jira/software/c/projects/MAR/boards/47?modal=detail&selectedIssue=MAR-2510&assignee=61acf073977c5b0072556985
description:
Added adaptability to banner 
tests:

Mar 2510. Added adaptability to banner 

---

client/components/core/banners/MadCommunityBanner.vue

task:
https://maddevs.atlassian.net/jira/software/c/projects/MAR/boards/47?modal=detail&selectedIssue=MAR-2510&assignee=61acf073977c5b0072556985
description:
hotfix button position. changed background image to new SVG

MAR-2510. hotfix button position. changed background image to new SVG

---

nuxt.config.js
server/config/json/blog-redirects.json
server/config/json/careers-redirect.json
server/config/json/customer-university-redirects.json
server/config/json/hr-tags-redirects.json
server/config/json/invalid-links-redirects.json
server/middlewares/redirectToCorrectBlogUrl.js
server/middlewares/redirectToValidLink.js
server/middlewares/tests/redirectHrTags.test.js
server/middlewares/tests/redirectInvalidLinks.spec.js
server/middlewares/tests/redirectToCorrectBlogUrl.test.js
server/middlewares/tests/redirectToCustomerUrl.test.js
server/middlewares/tests/redirectToValidLink.spec.js

> [MAR-1445](https://maddevs.atlassian.net/browse/MAR-1445)
1. Removed trailingSlash.
2. Fixed middlewares for url without trailingSlash.
3. Fixed redirects.
4. Updated tests for staging

MAR-1445 Fix bugs with trailingSlash and redirects

---

server/radiator/index.js

1) hid the graphics in the daily radiator

MAR-1762 hid the graphics in the daily radiator

---

server/radiator/index.js

Reverts maddevsio/maddevs#1732

Revert "MAR-1762 hid the graphics in the daily radiator"

---

client/components/Careers/CTABanner.vue
client/locales/en.json
tests/unit/components/Careers/__snapshots__/CTABanner.spec.js.snap

task: https://maddevs.atlassian.net/jira/software/c/projects/MAR/boards/47?modal=detail&selectedIssue=MAR-2698&assignee=61acf073977c5b0072556985
description: MAR-2698. changed text in CTA banner and added some styles
tests:

MAR-2698. changed text in CTA banner and added some styles

---

.slicemachine/assets/client/prismicSlices/pageParts/TextSlice/index.stories.js
.slicemachine/assets/client/prismicSlices/pageParts/TextSlice/mocks.json
client/prismicSlices/pageParts/TextSlice/model.json
client/prismicSlices/pageParts/TextSlice/variations/FlexibleParagraph.vue
nuxt.config.js
tests/unit/prismicSlices/pageParts/TextSlice/__snapshots__/index.spec.js.snap
tests/unit/prismicSlices/pageParts/TextSlice/variations/FlexibleParagraph.spec.js
tests/unit/prismicSlices/pageParts/TextSlice/variations/__snapshots__/FlexibleParagraph.spec.js.snap

the task: https://maddevs.atlassian.net/browse/MAR-2708
1. Deleted old props from FlexibleParagraph slice

MAR-2708. Deleted old props from FlexibleParagraph slice

---

client/prismicSlices/pageParts/TitleAndParagraphSlice/index.vue

Hot fix - imported linkResolver

MAR-2708. Fixed problems: imported linkResolver

---

client/prismicSlices/pageParts/PressCenter/index.vue

task: https://maddevs.atlassian.net/jira/software/c/projects/MAR/boards/47?modal=detail&selectedIssue=MAR-2560&assignee=61acf073977c5b0072556985
description: fixed card width
added target to links
preview:

MAR-2560. fixed bugs

---

client/prismicSlices/pageParts/EmbedSlice/index.vue

the task: https://maddevs.atlassian.net/browse/MAR-2714
1. Added margin-bottom to block Embed

MAR-2714. Added margin-bottom to the block Embed

---

client/prismicSlices/pageParts/TechnologiesAndTools/variations/TechnologiesAndTools.vue
client/prismicSlices/pageParts/TechnologiesSlice/index.vue
tests/unit/components/Cases/godee/__snapshots__/BeforeAfter.spec.js.snap
tests/unit/components/Cases/godee/__snapshots__/Main.spec.js.snap
tests/unit/components/core/Footer/__snapshots__/Footer.spec.js.snap
tests/unit/components/core/Footer/__snapshots__/FooterNavbar.spec.js.snap
tests/unit/components/core/Footer/__snapshots__/FooterNavbarMobile.spec.js.snap

the task: https://maddevs.atlassian.net/browse/MAR-2624
1. Fixed a problem with re-running the animation

MAR-2624. Fixed an issue with re-running animation

---

server/index.js
server/middlewares/redirectToCorrectBlogUrl.js
server/middlewares/tests/redirectToCorrectBlogUrl.test.js
server/middlewares/tests/redirectToRuCareerPostUrl.test.js

> [MAR-2663](https://maddevs.atlassian.net/browse/MAR-2663)
- Created middleware for blog redirects.
- Created tests.

MAR-2663. Fix blog redirects

---

client/components/Careers/shared/PositionsGridItem.vue
server/middlewares/redirectToRuCareerPostUrl.js
tests/unit/components/Careers/shared/__snapshots__/PositionsGridItem.spec.js.snap

1. Fixed redirects to career pages

MAR-2663. Fixed redirects to career pages

---

client/components/Blog/Main/NewCustomerUniversitySection.vue
client/components/Blog/Post/Post.vue
client/components/Blog/shared/CustomerUniversityCard.vue
client/components/core/HeaderV2/HeaderPost.vue
client/components/core/modals/ModalSearch.vue
client/data/deliveryModels.js
client/data/seo.js
client/mixins/buildBlogPostMixin.js
client/pages/author/_uid.vue
client/pages/blog/search-result/index.vue
client/pages/tag/_uid.vue
client/plugins/link-resolver.js
tests/unit/components/Blog/shared/PostAuthor.spec.js
utils/getRoutes.js

> [MAR-2751](https://maddevs.atlassian.net/browse/MAR-2751)
- Fixed canonical urls.
- Fixed redirect loop.
- Fixed redirects.

MAR-2751. Fixed canonical urls and redirects

---

server/config/json/mainRedirects.json

> [MAR-2663](https://maddevs.atlassian.net/browse/MAR-2663)
Fixed design redirects

MAR-2663. Fixed design redirects

---

client/components/Blog/header/Blog.vue
client/components/slices/AuthorSlice.vue
client/helpers/extractPostData.js
client/mixins/buildBlogPostMixin.js
client/store/modules/blogAuthors.js
tests/unit/components/Blog/header/__snapshots__/Blog.spec.js.snap

task: https://maddevs.atlassian.net/jira/software/c/projects/MAR/boards/47?modal=detail&selectedIssue=MAR-2556&assignee=61acf073977c5b0072556985
description: Added coauthor to blog pages.
example:

MAR-2556. Added coauthor to blog pages 

---

client/components/slices/AuthorSlice.vue
tests/unit/components/slices/AuthorSlice.spec.js
tests/unit/components/slices/__snapshots__/AuthorSlice.spec.js.snap

task: https://maddevs.atlassian.net/jira/software/c/projects/MAR/boards/47?modal=detail&selectedIssue=MAR-2556&assignee=61acf073977c5b0072556985
description: Fixed margin between photo and author name
example:

MAR-2556. Fixed margin between photo and author name

---

server/config/json/mainRedirects.json
server/index.js
server/middlewares/redirectToCorrectAuthorUrl.js
server/middlewares/redirectToCorrectSoftwateTestingUrl.js
server/middlewares/tests/redirectToCorrectAuthorUrl.test.js
server/middlewares/tests/redirectToCorrectSoftwateTestingUrl.test.js
tests/unit/components/Blog/Post/__snapshots__/Post.spec.js.snap
tests/unit/components/Blog/header/__snapshots__/Blog.spec.js.snap
tests/unit/components/Blog/shared/__snapshots__/CustomerUniversityCard.spec.js.snap
tests/unit/components/Blog/shared/__snapshots__/FeaturedPost.spec.js.snap
tests/unit/components/Blog/shared/__snapshots__/PostCard.spec.js.snap
tests/unit/components/Blog/shared/__snapshots__/PostTag.spec.js.snap
tests/unit/components/core/HeaderV2/HeaderPost.spec.js
tests/unit/components/core/HeaderV2/__snapshots__/HeaderPost.spec.js.snap
tests/unit/components/core/modals/ModalSearch.spec.js
tests/unit/components/slices/__snapshots__/AuthorSlice.spec.js.snap
tests/unit/pages/approach/delivery-models/index.spec.js
tests/unit/pages/blog/author/_uid/_uid.spec.js
tests/unit/pages/blog/tag/_uid/index.spec.js
tests/unit/pages/privacy.spec.js
tests/unit/plugins/link-resolver.spec.js

> [MAR-2751](https://maddevs.atlassian.net/browse/MAR-2751)
- Added new redirects. 
- Added new middlewares for new urls. 
- Added 2 tests for middlewares.
-  Updated and fix 25 unit tests

MAR-2751 Fix redirects and tests

---

nuxt.config.js
server/config/json/mainRedirects.json
server/controllers/SitemapController.js
server/controllers/tests/SitemapController.spec.js
server/middlewares/redirectToValidLink.js
server/middlewares/tests/redirectToValidLink.spec.js
tests/unit/getRobots.spec.js
utils/getRobots.js
utils/getRoutes.js
utils/getSitemap.js

> [MAR-2670](https://maddevs.atlassian.net/browse/MAR-2670)
- Refactoring getRoutes.
- Created getSitemap.
- New structure for sitemap.
- Refactoring nuxt.config.js.

MAR-2670. New sitemap structure

---

README.md
package-lock.json
package.json
tests/unit/components/Blog/Post/__snapshots__/Post.spec.js.snap
tests/unit/components/Blog/header/__snapshots__/Blog.spec.js.snap
tests/unit/components/Blog/shared/__snapshots__/CustomerUniversityCard.spec.js.snap
tests/unit/components/Blog/shared/__snapshots__/FeaturedPost.spec.js.snap
tests/unit/components/Blog/shared/__snapshots__/PostCard.spec.js.snap
tests/unit/components/Blog/shared/__snapshots__/PostTag.spec.js.snap

the task: https://maddevs.atlassian.net/browse/MAR-2785
1. Updated Readme and changed version of Node

MAR-2785. Updated Readme and changed version of Node

---

client/components/Cases/shared/Swiper.vue
client/components/Cases/sjmc/Office.vue
client/components/Cases/sjmc/SystemMonitoring.vue
client/components/Cases/sjmc/Trip.vue
tests/unit/components/Cases/citycam/__snapshots__/DevicePerfecting.spec.js.snap
tests/unit/components/Cases/citycam/__snapshots__/OngoingProgress.spec.js.snap
tests/unit/components/Cases/namba-food/__snapshots__/Swift.spec.js.snap
tests/unit/components/Cases/shared/__snapshots__/Swiper.spec.js.snap

1) https://maddevs.atlassian.net/browse/MAR-2803
2) Description: 
Bugfix component Swiper
Removed properties for safari on SJMC page
Updated snapshots
3)

MAR-2803. Bugfix component Swiper and Removed prop for safari on SJMC

---

client/components/Cases/yourcast/AboutYourcast.vue
client/components/Cases/yourcast/CardProjectInNumbers.vue
tests/unit/components/Cases/yourcast/__snapshots__/AboutYourcast.spec.js.snap
tests/unit/components/Cases/yourcast/__snapshots__/CardProjectInNumbers.spec.js.snap
tests/unit/components/Cases/yourcast/__snapshots__/Main.spec.js.snap
tests/unit/components/Cases/yourcast/__snapshots__/ProjectInNumbers.spec.js.snap

1. https://maddevs.atlassian.net/browse/MAR-627
2. Description: 
Changed quote text in AboutYourcast.
Disabled animation and corrected text in Project in numbers.
Updated snapshots.
3.

MAR-627. Fixed text and disable animation.

---

client/components/Cases/guardrails/Main.vue
client/components/Cases/guardrails/ResultsAndAchievements.vue

1) https://maddevs.atlassian.net/browse/MAR-66
2) Removed counter from Results and Achievements block
3)

MAR-66. Removed counter from Results and Achievements block

---

client/components/Cases/guardrails/About.vue
client/components/Cases/guardrails/AgilityIsKey.vue
client/components/Cases/guardrails/ApiForDashboard.vue
client/components/Cases/guardrails/Dashboard.vue
client/components/Cases/guardrails/ProjectIssues.vue
client/components/Cases/guardrails/TechnicalAgility.vue

1) https://maddevs.atlassian.net/jira/software/c/projects/MAR/boards/47?modal=detail&selectedIssue=MAR-66&assignee=61acf073977c5b0072556985
2) Added spaces in text content.
3)

MAR-66. Added spacen in text content.

---

client/components/core/modals/ModalContentLocker.vue

1. https://maddevs.atlassian.net/browse/MAR-2662
2. Description:
Fix centering title in pop-up.
3.

MAR-2662. Fix centering title in pop-up.

---

client/mixins/createLeadMixin.js
server/services/LeadsService.js

https://maddevs.atlassian.net/browse/MAR-2896

MAR-2896. Added interest field to Contact me form for Jira

---

server/services/LeadsService.js

https://maddevs.atlassian.net/browse/MAR-2896

MAR-2896. fixed custom field

---

server/services/LeadsService.js
server/services/tests/LeadsService.spec.js

https://maddevs.atlassian.net/browse/MAR-2896

MAR-2896. updated tests

---

client/api/header.js
client/store/modules/header.js

1. https://maddevs.atlassian.net/browse/MAR-2880
2. Fix header requests to prismic. 
Instead of 12 requests, now 1
3.

MAR-2880. Fix Header requests to prismic.

---

jest/utils/sendCoverageToSlack.js
package-lock.json
package.json

1. https://maddevs.atlassian.net/browse/MAR-2902
2. Deleted plugin request. Replaced with Axios.

MAR-2902. Deleted plugin request. Replaced with axios.

---

client/components/Cases/peklo/Main.vue
tests/unit/components/Cases/peklo/Main.spec.js
tests/unit/components/Cases/peklo/__snapshots__/Main.spec.js.snap

1) https://maddevs.atlassian.net/browse/MAR-2917
2) Added LazyHydrate to Peklo case.

MAR-2917. Added LazyHydrate to Peklo case. 

---

client/components/Cases/clutch/Main.vue
client/modules/js-optimizer.js
client/prismicSlices/pageParts/TechnologiesSlice/index.vue
nuxt.config.js
package-lock.json
package.json
tests/unit/components/Cases/peklo/Main.spec.js
tests/unit/prismicSlices/pageParts/ButtonSlice/index.spec.js
tests/unit/prismicSlices/pageParts/CustomerTestimonials/index.spec.js
tests/unit/prismicSlices/pageParts/GridLottieSlice/index.spec.js
tests/unit/prismicSlices/pageParts/KeyMetricsSlice/index.spec.js

1. https://maddevs.atlassian.net/browse/MAR-2911
2. Added new module for optimization JS.
Added new options to nuxt.config for optimization.
Updated unit tests for dymanic imports.

MAR-2911. Added new module for optimization JS.

---

nuxt.config.js
package.json

> [MAR-2920](https://maddevs.atlassian.net/browse/MAR-2920)
Ignored client/modules for heroku-cleanup

MAR-2920 Fix heroku 

---

client/app/router.scrollBehavior.js
client/prismicSlices/pageParts/TextSlice/variations/Title.vue

https://maddevs.atlassian.net/browse/MAR-2918
fixed autoscroll, fixed copping anchor link. fixed spacing to anchor link

MAR-2918. fixed autoscroll, fixed copping anchor link. fixed spacing to anchor link

---

client/components/Cases/CasesList.vue
client/pages/case-studies/index.vue
nuxt.config.js
tests/unit/pages/case-studies/__snapshots__/index.spec.js.snap
tests/unit/pages/case-studies/index.spec.js

the task: https://maddevs.atlassian.net/browse/MAR-2924
1. Wrapped components in the LazyHydrate
2. Fixed tests

MAR-2924. Wrapped components in the LazyHydrate

---

nuxt.config.js
package-lock.json
package.json

the task: https://maddevs.atlassian.net/browse/MAR-2914
1. Deleted the swiper package

MAR-2914. Deleted the swiper package

---

client/components/Cases/nambafood/Main.vue
client/prismicSlices/pageParts/TextSlice/index.vue
tests/unit/components/Cases/clutch/Main.spec.js
tests/unit/components/Cases/clutch/__snapshots__/Main.spec.js.snap
tests/unit/components/Cases/namba-food/Main.spec.js
tests/unit/components/Cases/namba-food/__snapshots__/Main.spec.js.snap
tests/unit/components/Cases/yourcast/Main.spec.js
tests/unit/prismicSlices/pageParts/ButtonSlice/index.spec.js
tests/unit/prismicSlices/pageParts/CustomerTestimonials/index.spec.js
tests/unit/prismicSlices/pageParts/GridLottieSlice/index.spec.js
tests/unit/prismicSlices/pageParts/KeyMetricsSlice/index.spec.js
tests/unit/prismicSlices/pageParts/TechnologiesAndTools/index.spec.js
tests/unit/prismicSlices/pageParts/TextSlice/index.spec.js

1. https://maddevs.atlassian.net/browse/MAR-2925
2. Namba Food: Wrapped components in LazyHydrate.
Written unit tests for dynamic imports.
Rewrote all tests to dynamic imports.

MAR-2925. Namba Food: Wrapped components in LazyHydrate. 

---

tests/unit/components/Cases/sjmc/Main.spec.js

the task: https://maddevs.atlassian.net/browse/MAR-2927
1. Fixed tests

MAR-2928. Fixed tests

---

client/components/Cases/TitleDesc.vue
tests/unit/pages/case-studies/index.spec.js

the task: https://maddevs.atlassian.net/browse/MAR-2928
1. Fixed tests

MAR-2927. Fixed tests

---

client/components/Cases/veeqo/Main.vue
tests/unit/components/Cases/peklo/Main.spec.js
tests/unit/components/Cases/veeqo/Main.spec.js
tests/unit/components/Cases/veeqo/__snapshots__/Main.spec.js.snap
tests/unit/components/Cases/yourcast/Main.spec.js

1) https://maddevs.atlassian.net/browse/MAR-2917
2) 
Peklo: Added tests to dynamic imports
Yourcast: Fixed tests variables

MAR-2922. Peklo: Added tests to dynamic imports

---

tests/unit/components/Cases/veeqo/Main.spec.js

1) https://maddevs.atlassian.net/browse/MAR-2922 
2) Veeqo: Added tests to dynamic imports

MAR-2922. Veeqo: Added tests to dynamic imports

---

client/components/Cases/nambataxi/Main.vue
tests/unit/components/Cases/namba-taxi/Main.spec.js
tests/unit/components/Cases/namba-taxi/__snapshots__/Main.spec.js.snap

1. https://maddevs.atlassian.net/browse/MAR-2938
2.
Namba Taxi: Wrapped components in LazyHydrate.
Written unit tests for dynamic imports.

MAR-2938. Namba Taxi: Wrapped components in LazyHydrate.

---

client/components/About/CustomerTestimonials.vue
client/components/Cases/itc/Main.vue
client/components/Cases/itc/ProjectMission.vue
tests/unit/components/Cases/itc/Main.spec.js
tests/unit/components/Cases/itc/__snapshots__/Main.spec.js.snap

the task: https://maddevs.atlassian.net/browse/MAR-2934
2. Fixed tests

MAR-2934. Wrapped component in the LazyHydrate

---

client/components/Cases/guardrails/AgilityIsKey.vue
client/components/Cases/guardrails/ApiForDashboard.vue
client/components/Cases/guardrails/CliandKubernetes.vue
client/components/Cases/guardrails/Dashboard.vue
client/components/Cases/guardrails/Main.vue
client/components/Cases/guardrails/ResultsAndAchievements.vue
tests/unit/components/Cases/guardrails/Main.spec.js
tests/unit/components/Cases/guardrails/__snapshots__/Main.spec.js.snap

1) https://maddevs.atlassian.net/browse/MAR-2937
2)
Added dynamic imports and tests to guardrails
Fixed components names

MAR-2937. Guardrails: fixed components names

---

client/components/Cases/CasesList.vue
client/components/Cases/CasesListItem.vue
client/pages/case-studies/index.vue
tests/unit/components/Cases/CasesList.spec.js
tests/unit/components/Cases/__snapshots__/CasesList.spec.js.snap
tests/unit/components/core/__snapshots__/CaseStudies.spec.js.snap
tests/unit/pages/case-studies/__snapshots__/index.spec.js.snap

the task: https://maddevs.atlassian.net/browse/MAR-2928
2. Fixed test and updated snapshots

MAR-2928. Wrapped the component in the LazyHydrate

---

client/pages/gdpr.vue
tests/unit/pages/__snapshots__/gdpr.spec.js.snap
tests/unit/pages/gdpr.spec.js

the subtask: https://maddevs.atlassian.net/browse/MAR-2959
2. Fixed tests

MAR-2959. GDPR: Wrapped the component in the LazyHydrate

---

client/pages/nda.vue
tests/unit/pages/__snapshots__/nda.spec.js.snap
tests/unit/pages/nda.spec.js

the subtask: https://maddevs.atlassian.net/browse/MAR-2955
2. Fixed test

MAR-2955. Wrapped the component in the LazyHydrate

---

client/pages/faq.vue
tests/unit/pages/__snapshots__/faq.spec.js.snap
tests/unit/pages/faq.spec.js

the subtask: https://maddevs.atlassian.net/browse/MAR-2954
2. Fixed tests

MAR-2954. Wrapped the component in the LazyHydrate

---

client/components/slices/CodeBlockSlice/index.vue
client/components/slices/index.vue
tests/unit/components/slices/__snapshots__/index.spec.js.snap
tests/unit/components/slices/index.spec.js

the subtask: https://maddevs.atlassian.net/browse/MAR-2962
1. Wrapped components in the LazyHydrate
2. Fixed tests

MAR-2962. Blog (the main index.vue file): components wrapped in the LazyHydrate

---

client/components/OpenSource/Main.vue
tests/unit/components/OpenSource/Main.spec.js
tests/unit/components/OpenSource/__snapshots__/Main.spec.js.snap

the subtask: https://maddevs.atlassian.net/browse/MAR-2964
1. Wrapped components in the LazyHydrate
2. Fixed tests

MAR-2964. Open-source (Main component): wrapped components in the LazyHydrate

---

client/components/Careers/EmployeesBenefits.vue
client/components/Careers/Main.vue
client/components/Careers/OpenPositions.vue
client/components/Careers/shared/PositionsGrid.vue
nuxt.config.js
tests/unit/components/Careers/EmployeesBenefits.spec.js
tests/unit/components/Careers/Main.spec.js
tests/unit/components/Careers/OpenPositions.spec.js
tests/unit/components/Careers/__snapshots__/EmployeesBenefits.spec.js.snap
tests/unit/components/Careers/__snapshots__/Main.spec.js.snap
tests/unit/components/Careers/__snapshots__/OpenPositions.spec.js.snap

1. https://maddevs.atlassian.net/browse/MAR-2965
2.
Careers: Wrapped components in LazyHydrate.
Written unit tests for dynamic imports.

MAR-2965. Careers: Wrapped components in LazyHydrate.

---

client/components/Cases/clutch/WidgetSpeed.vue
client/components/Cases/godee/ParallaxImage.vue
client/components/Cases/guardrails/Dashboard.vue
client/components/Cases/itc/Challenges.vue
client/components/Cases/shared/ParallaxCards/ParallaxCards.vue
client/components/Cases/veeqo/ContinuousIntegrationResult.vue
client/components/Cases/veeqo/HighLevelOverview.vue
client/components/Cases/veeqo/InventoryChangeLog.vue
client/components/Cases/veeqo/PhasInfrastructureAsCodeResult.vue
client/components/Cases/veeqo/PhaseElasticsearchResult.vue
client/plugins/mad-parallax.js
nuxt.config.js
tests/unit/components/Cases/veeqo/__snapshots__/ContinuousIntegrationResult.spec.js.snap
tests/unit/components/Cases/veeqo/__snapshots__/HighLevelOverview.spec.js.snap
tests/unit/components/Cases/veeqo/__snapshots__/InventoryChangeLog.spec.js.snap
tests/unit/components/Cases/veeqo/__snapshots__/PhasInfrastructureAsCodeResult.spec.js.snap
tests/unit/components/Cases/veeqo/__snapshots__/PhaseElasticsearchResult.spec.js.snap
tests/unit/plugins/mad-parallax.spec.js

1. https://maddevs.atlassian.net/browse/MAR-3012
2.
Wrote unit tests for the parallax plugin.
Slightly redesigned the plugin itself and its call in the components

MAR-3012. Wrote unit tests for the parallax plugin.

---

client/plugins/google-tag-manager-debug.js
client/plugins/sentry.js

1) https://maddevs.atlassian.net/browse/MAR-2912
2) Disabled Sentry and GTM on staging and local dev.

MAR-2912. Disabled Sentry and GTM on staging and local dev.

---

client/components/core/forms/BaseForm.vue
client/prismicSlices/pageParts/ContactsSlice/components/OrderForm.vue
server/services/LeadsService.js

> [MAR-3090](https://maddevs.atlassian.net/browse/MAR-3090)
Fixed integration with jira for forms

MAR-3090 Fix order form

---

client/components/Cases/guardrails/ApiForDashboard.vue
client/components/Cases/guardrails/CliandKubernetes.vue
client/components/Cases/guardrails/Dashboard.vue

the subtask: https://maddevs.atlassian.net/browse/MAR-3019
1. Added widths & heights to images

MAR-3019. Added widths & heights to images

---

client/prismicSlices/pageParts/TechnologiesAndTools/components/ToolsGrid.vue

1. https://maddevs.atlassian.net/browse/MAR-3015
2. Fix duplicate keys in Tech Stack.

MAR-3015. Fix duplicate keys in Tech Stack.

---

client/components/Blog/Post/Post.vue
client/components/slices/TextSlice.vue
client/prismicSlices/pageParts/TextSlice/variations/Title.vue
tests/unit/components/Blog/Post/Post.spec.js
tests/unit/components/slices/TextSlice.spec.js
tests/unit/prismicSlices/pageParts/TextSlice/variations/Title.spec.js

1. https://maddevs.atlassian.net/browse/MAR-3025
2. Fix anchor links
Fix unit tests
3.

MAR-3025. Fix anchor links

---

client/pages/_uid.vue
client/plugins/sentry.js
nuxt.config.js

[MAR-3027 Fix Sentry](https://maddevs.atlassian.net/browse/MAR-3027)
> Fixed scope for sentry plugin

MAR-3027 Fix Sentry

---

client/components/Blog/shared/CustomerUniversityCard.vue

[MAR-3030 Fix images for blog page](https://maddevs.atlassian.net/browse/MAR-3030)
> Fixed featured imageg for blog page

MAR-3030 Fix images for blog page

---

server/services/IPService.js

[MAR-3028 Fix getting ip](https://maddevs.atlassian.net/browse/MAR-3028)
> Add console.log for ip

MAR-3028 Fix getting ip

---

client/components/core/HeaderV2/index.vue
nuxt.config.js
tests/unit/components/core/HeaderV2/__snapshots__/index.spec.js.snap

the task: https://maddevs.atlassian.net/browse/MAR-3031
1. Fixed position of bread crumbs
2. Fixed nuxt.config.js

MAR-3031. Fixed position of bread crumbs

---

client/components/Cases/bandpay/IntegratingOnline.vue
client/components/Cases/bandpay/WhatIsBackend.vue
client/components/Cases/shared/ColoredCards/ColoredCard.vue
client/components/Cases/shared/ColoredCards/index.vue
client/components/core/HeaderV2/index.vue
client/data/caseBandpay.js
client/pages/case-studies/bandpay.vue

1. https://maddevs.atlassian.net/browse/MAR-1259
2. 
Fix font-size for top footer title block.
Fix header crumbs.
Rename props name for centered title for colored cards.

MAR-1259. Fix font-size for top footer title block.

---

client/components/Cases/bandpay/IntegratingOnline.vue
client/components/Cases/bandpay/WhatIsBackend.vue

1. https://maddevs.atlassian.net/browse/MAR-1259
2.
Fix paddings and block with stripe logo and list with check marks

MAR-1259. Fix paddings and block with stripe logo and list with check marks

---

client/components/Cases/bandpay/IntegratingOnline.vue
client/components/Cases/bandpay/WhatIsBackend.vue

1. https://maddevs.atlassian.net/browse/MAR-1259
2. Fixed style priority.

MAR-1259. Fixed style priority.

---

client/helpers/setSliceBackground.js
client/prismicSlices/pageParts/AwardsSlice/index.vue
client/prismicSlices/pageParts/BenefitSlice/index.vue
client/prismicSlices/pageParts/ButtonSlice/index.vue
client/prismicSlices/pageParts/CardGridSlice/index.vue
client/prismicSlices/pageParts/CardGridSlice/variations/CardGridWithIcon.vue
client/prismicSlices/pageParts/CaseListSlice/index.vue
client/prismicSlices/pageParts/CreateProjectsSlice/index.vue
client/prismicSlices/pageParts/CustomerLogoSlice/index.vue
client/prismicSlices/pageParts/DescriptionSliceWithIcon/index.vue
client/prismicSlices/pageParts/GridLottieSlice/index.vue
client/prismicSlices/pageParts/ImageSlice/index.vue
client/prismicSlices/pageParts/KeyMetricsSlice/index.vue
client/prismicSlices/pageParts/KeyMetricsSlice/variations/SecondVariation.vue
client/prismicSlices/pageParts/KeyMetricsSlice/variations/ThirdVariation.vue
client/prismicSlices/pageParts/NavLinkSlice/index.vue
client/prismicSlices/pageParts/ProgressSlice/index.vue
client/prismicSlices/pageParts/ProjectStartSlice/index.vue
client/prismicSlices/pageParts/SpacerSlice/index.vue
client/prismicSlices/pageParts/StartScreen/index.vue
client/prismicSlices/pageParts/TechnologiesAndTools/index.vue
client/prismicSlices/pageParts/TextSlice/index.vue
client/prismicSlices/pageParts/VideoSlice/index.vue
client/prismicSlices/pageParts/WeCreateProjectsFor/index.vue
tests/unit/prismicSlices/pageParts/CustomerLogoSlice/__snapshots__/index.spec.js.snap
tests/unit/prismicSlices/pageParts/GridLottieSlice/__snapshots__/index.spec.js.snap
tests/unit/prismicSlices/pageParts/GridLottieSlice/index.spec.js
tests/unit/prismicSlices/pageParts/StartScreen/index.spec.js
tests/unit/prismicSlices/pageParts/TechnologiesAndTools/__snapshots__/index.spec.js.snap

https://maddevs.atlassian.net/browse/MAR-2980
Refactoring slices computed properties. 
Changed slice background and color theme selector method to helper methods

MAR-2980-merge-conflicts

---

client/components/Blog/shared/PostAuthor.vue

1. https://maddevs.atlassian.net/browse/MAR-2748
2. Redesign Post Author component.

MAR-2748. Redesign Post Author component.

---

client/components/core/HeaderV2/index.vue
client/components/shared/Crumbs.vue

the task: https://maddevs.atlassian.net/browse/MAR-3066
1. Refactored bread crumbs
2. Added conditional operator that checks for existence title

MAR-3066. Refactored breadcrumbs

---

.slicemachine/assets/client/prismicSlices/pageParts/CardWithImageSlice/index.stories.js
.slicemachine/assets/client/prismicSlices/pageParts/CardWithImageSlice/mocks.json
.slicemachine/assets/client/prismicSlices/pageParts/TextList/index.stories.js
.slicemachine/assets/client/prismicSlices/pageParts/TextList/mocks.json
.slicemachine/libraries-state.json
.slicemachine/mock-config.json
client/helpers/setSliceBackground.js
client/prismicSlices/pageParts/CardWithImageSlice/index.vue
client/prismicSlices/pageParts/CardWithImageSlice/model.json
client/prismicSlices/pageParts/TextList/index.vue
client/prismicSlices/pageParts/TextList/model.json
tests/unit/prismicSlices/pageParts/TextSlice/__snapshots__/index.spec.js.snap
tests/unit/prismicSlices/pageParts/TextSlice/index.spec.js

1. [MAR-3080: Внести правки в верстку слайсов для вложенных страниц Service](https://maddevs.atlassian.net/browse/MAR-3080)
2. Add a list variation without a title.
Fixed the problem of a cropped image when there is not enough text.
Fixed test TextSlice.

MAR-3080. Fixed the problem of a cropped image when there is not enough text.

---

client/components/shared/UIBeforeAfterImage.vue

the task: https://maddevs.atlassian.net/browse/MAR-3081
1. Deleted handleInput method
2. Used v-model in the input element
3. Deleted value attribute from the input element
4. Updated snapshots

MAR-3081. Deleted handleInput method and used v-model

---

client/components/Blog/Main/NewCustomerUniversitySection.vue
client/components/shared/Crumbs.vue
tests/unit/components/Blog/Main/__snapshots__/NewCustomerUniversitySection.spec.js.snap
tests/unit/components/shared/__snapshots__/Crumbs.spec.js.snap

the task: https://maddevs.atlassian.net/browse/MAR-3084
1. Added the anchor link to the CU section on the blog main page
2. Added condition to check the breadcrumb
From:
To:

MAR-3084. Added the anchor link to CU section on the blog main page

---

.slicemachine/assets/client/prismicSlices/pageParts/CardWithImageSlice/index.stories.js
.slicemachine/assets/client/prismicSlices/pageParts/CardWithImageSlice/mocks.json
.slicemachine/libraries-state.json
.slicemachine/mock-config.json
client/prismicSlices/pageParts/CardWithImageSlice/index.vue
client/prismicSlices/pageParts/CardWithImageSlice/model.json
client/prismicSlices/pageParts/TextList/index.vue
tests/unit/prismicSlices/pageParts/CardWithImageSlice/__snapshots__/index.spec.js.snap
tests/unit/prismicSlices/pageParts/CardWithImageSlice/index.spec.js
tests/unit/prismicSlices/pageParts/TextList/__snapshots__/index.spec.js.snap
tests/unit/prismicSlices/pageParts/TextList/index.spec.js

1. [Верстка слайсов для обновленных вложенных страниц](https://maddevs.atlassian.net/browse/MAR-2933)
2. Redesign cards with image.
Replaced a regular text field with a field with a title selection. 
Added unit tests for services slices.
Updated snapshots.

MAR-2933. Added unit tests for services slices. Redesing cards with image.

---

nuxt.config.js

[MAR-3089 Fix Sentry ignore](https://maddevs.atlassian.net/browse/MAR-3098)
> - Fixed ignoreErrors
> - Fixrd denyUrl

MAR-3089 Fix Sentry ignore

---

client/components/shared/Crumbs.vue
nuxt.config.js

[MAR-3090 Фикс игнора для Sentry](https://maddevs.atlassian.net/browse/MAR-3098)

Deploy to prod

---

client/components/Blog/Post/CustomerUniversityNavigation.vue
client/components/Blog/Post/Post.vue
tests/unit/components/Blog/Post/CustomerUniversityNavigation.spec.js
tests/unit/components/Blog/Post/__snapshots__/CustomerUniversityNavigation.spec.js.snap

the task: https://maddevs.atlassian.net/browse/MAR-2589
1. Deleted title and the cluster prop
2. Added space between slider and comments block
3. Fixed tests
4. Updated snapshots

MAR-2589. Fixed some bugs and updated tests

---

server/controllers/LeadsController.js
server/services/LeadsService.js
server/services/tests/LeadsService.spec.js

[MAR-3132 New fields for jira](https://maddevs.atlassian.net/browse/MAR-3132)
> - Added new fields
> - Updated tests

MAR-3132 New fields for jira

---

client/components/core/FooterV2/Footer.vue
client/components/core/FooterV2/FooterNavbar.vue

MAR-2919. Footerv2

---

client/components/core/HeaderV2/HeaderPost.vue

1. [В хедере не работает переход по посту CU](https://maddevs.atlassian.net/browse/MAR-3065)
2. Fixed url link to CU posts in header.

MAR-3065. Fixed url link to CU posts in header.

---

client/components/Blog/Main/AuthorPostsSection.vue
client/components/Blog/shared/PostCard.vue
tests/unit/components/Blog/Main/__snapshots__/AuthorPostsSection.spec.js.snap
tests/unit/components/Blog/shared/__snapshots__/PostCard.spec.js.snap

1. [Исправить баг по верстке на странице автора ](https://maddevs.atlassian.net/browse/MAR-3113)
2. Fixed a bug in the height of post cards of authors.
Updated snapshots.

MAR-3113. Fixed a bug in the height of post cards of authors

---

client/components/core/chat/ChatModal/DevelopmentBody/index.vue
client/components/core/chat/ChatModal/MainBody/index.vue
client/components/core/forms/BaseForm.vue
client/components/core/forms/ContactMeForm.vue

The task: https://maddevs.atlassian.net/browse/MAR-2704
1. Fixed styles
2. Added a conditional operator to check the useCompany option

MAR-3177. Fixed styles and logic

---

client/components/Ebook/ReadForm.vue
server/services/LeadsService.js
server/services/tests/LeadsService.spec.js
tests/unit/components/Ebook/ReadForm.spec.js

The task: https://maddevs.atlassian.net/browse/MAR-3162
1. Updated the logic
2. Fixed tests

MAR-3162. Changed logic to create leads on the board

---

client/components/Ebook/ReadForm.vue
client/components/core/modals/ModalContentLocker.vue

the task: https://maddevs.atlassian.net/browse/MAR-3162
1. Used option for the formLocation from props

MAR-3162. Fixed formLocation name.

---

client/components/core/chat/ChatModal/DevelopmentBody/index.vue
server/services/LeadsService.js
server/services/tests/LeadsService.spec.js

the task: https://maddevs.atlassian.net/browse/MAR-3214
1. Deleted the custom_field 10190
2. Fixed tests

MAR-3214. Fixed problems

---

client/layouts/default.vue

1. Fixed style - deleted media query

MAR-3214. Fixed style

---

client/components/slices/EbookForm.vue
tests/unit/components/slices/EbookForm.spec.js

1. Fixed logic to send data from the ebook form

MAR-3214-ebook. Fixed problems

---

client/components/Cases/BuildDevTeam.vue
client/components/DeliveryModels/CTABanner.vue
tests/unit/components/Cases/__snapshots__/BuildDevTeam.spec.js.snap
tests/unit/components/DeliveryModels/__snapshots__/CTABanner.spec.js.snap

the task: https://maddevs.atlassian.net/browse/MAR-3220
1. Changed the position

MAR-3220. Changed the position

---

.slicemachine/assets/client/prismicSlices/pageParts/EbooksWithFilterSlice/index.stories.js
.slicemachine/assets/client/prismicSlices/pageParts/EbooksWithFilterSlice/mocks.json
.slicemachine/libraries-state.json
client/api/ebooks.js
client/components/Ebook/EbookFilter.vue
client/components/Ebook/EbooksCard.vue
client/prismicSlices/pageParts/EbooksWithFilterSlice/index.vue
client/prismicSlices/pageParts/EbooksWithFilterSlice/model.json
client/store/modules/ebooks.js
tests/unit/components/Ebook/EbookFilter.spec.js
tests/unit/components/Ebook/__snapshots__/EbooksCard.spec.js.snap
tests/unit/prismicSlices/pageParts/EbooksWithFilterSlice/EbooksWithFilterSlice.spec.js
tests/unit/prismicSlices/pageParts/EbooksWithFilterSlice/__snapshots__/EbooksWithFilterSlice.spec.js.snap
tests/unit/store/ebooks.spec.js

1. [Сборка общей посадочной под ибуки](https://maddevs.atlassian.net/browse/MAR-3089)
2. Fix bugs. Alteration of the logic of filtering and pagination.
Pictures not related to Ebooks are just for tests, after tests they will be deleted in prismic

MAR-3089. Fix bugs. Alteration of the logic of filtering and pagination.

---

client/components/Ebook/EbookFilter.vue
client/prismicSlices/pageParts/EbooksWithFilterSlice/index.vue

1. [Внести правки в дизайне](https://maddevs.atlassian.net/browse/MAR-3229)
2. Made changes to the components.
Added indents and increased the scroll to the heading.

MAR-3229. Made changes to the components for Ebooks page.

---

client/components/Blog/Main/AuthorBanner.vue
client/components/Blog/Main/AuthorPostsSection.vue

1. https://maddevs.atlassian.net/browse/MAR-3130
2. Made changes to the output of tags and posts.

MAR-3130. Made changes to the output of tags and posts.

---

client/assets/styles/_vars.scss
client/prismicSlices/pageParts/TeamCards/index.vue
tests/unit/prismicSlices/pageParts/TeamCards/__snapshots__/index.spec.js.snap
tests/unit/prismicSlices/pageParts/TeamCards/index.spec.js

the task: https://maddevs.atlassian.net/browse/MAR-3234
1. Deleted the lazy-load, changed data-src to src
2. Fixed test and updated snapshots

MAR-3234. Deleted lazy-load and changed data-src to src

---

client/components/Blog/Main/AuthorPostsSection.vue
tests/unit/components/Blog/Main/AuthorPostsSection.spec.js
tests/unit/components/Blog/Main/__snapshots__/AuthorPostsSection.spec.js.snap

1. [Обновить страницу автора ](https://maddevs.atlassian.net/browse/MAR-3130)
2. Bug Fixed button show all posts.

MAR-3130. Bug Fixed button show all posts.

---

client/components/Blog/Main/AuthorPostsSection.vue

1. https://maddevs.atlassian.net/browse/MAR-3130
2. Bug fixed height in posts card author.

MAR-3130. Bug fixed height in posts card author.

---

client/components/core/HeaderV2/index.vue
client/data/footerNavigation.js
client/store/modules/footer.js
client/store/modules/header.js
tests/unit/components/core/HeaderV2/__snapshots__/index.spec.js.snap
tests/unit/components/core/HeaderV2/index.spec.js

1) https://maddevs.atlassian.net/browse/MAR-3250
2) Added 'industries' department
3)

MAR-3250. Updated footer and header. 

---

client/pages/blog/authors/index.vue

1) Updated metadata for Authors page

MAR-3075. Updated metadata for Authors page 

---

client/pages/blog/authors/_uid.vue
client/pages/blog/authors/index.vue
server/config/json/mainRedirects.json
server/middlewares/redirectToCorrectUrl.js
tests/unit/pages/blog/authors/_uid/_uid.spec.js

the task: https://maddevs.atlassian.net/browse/MAR-3260
1. Fixed redirects
2. Updated a test

MAR-3260. Fixed redirects

---

client/components/Blog/header/Blog.vue
client/components/Blog/header/Common.vue
tests/unit/components/Blog/header/__snapshots__/Blog.spec.js.snap
tests/unit/components/Blog/header/__snapshots__/Common.spec.js.snap
tests/unit/components/Blog/header/__snapshots__/CustomerUniversity.spec.js.snap

the task: https://maddevs.atlassian.net/browse/MAR-3230
1. Fixed the date position, deleted margin and changed width

MAR-3230. Fixed the date position

---

utils/getRoutes.js

1. [Настроить sitemap под новые урлы авторов](https://maddevs.atlassian.net/browse/MAR-3267)
2. Fixed sitemap for new authors urls.

MAR-3267. Fixed sitemap for new authors urls.

---

package.json

1) https://maddevs.atlassian.net/browse/MAR-3222

MAR-3222. Script to update coverage badges 

---

client/components/core/forms/ContactMeForm.vue
client/components/shared/UIAccordion.vue
tests/unit/components/shared/__snapshots__/UIAccordion.spec.js.snap
tests/unit/prismicSlices/pageParts/AccordionSlice/__snapshots__/index.spec.js.snap

1. [Сборка страницы Saccess and FaQ](https://maddevs.atlassian.net/browse/MAR-3173)
2. Fixed bugs and remove animation for answers.

MAR-3173. Fixed bugs and remove animation for answers.

---

client/components/core/forms/ContactMeForm.vue
client/mixins/createLeadMixin.js

1. https://maddevs.atlassian.net/browse/MAR-3173
2. Fixed close contact me form when redirected.

MAR-3173. Fixed close contact me form when redirected.

---

client/prismicSlices/pageParts/CardWithImageSlice/index.vue

1. [Добавить межстрочный интервал в слайсе CardWithImageSlice](https://maddevs.atlassian.net/browse/MAR-3257)
2. Fixed styles for title in CardWithImageSlice.

MAR-3257. Fixed styles for title in CardWithImageSlice.

---

client/prismicSlices/pageParts/CustomerLogoSlice/index.vue

1. [Настроить CustomerLogoSlice в призмике](https://maddevs.atlassian.net/browse/MAR-3280)
2. Added centering of elements in the last line of the grid CustomerLogoSlice

MAR-3280. Added centering of elements in the CustomerLogoSlice.

---

client/analytics/Event.js
client/layouts/default.vue
client/plugins/gtag.js
client/plugins/vue-google-analytics.js
jest/configs/base.config.js
package-lock.json
package.json
tests/unit/analytics/Event.spec.js
tests/unit/components/DeliveryModels/shared/ModelCard.spec.js
tests/unit/prismicSlices/pageParts/CTABannerSlice/components/CTAModal.spec.js
tests/unit/prismicSlices/pageParts/CTABannerSlice/components/__snapshots__/CTAModal.spec.js.snap
utils/getPlugins.js

1. [Проверить код аналитики и понять причину не соответствия трафика между GA4 и UA](https://maddevs.atlassian.net/browse/MAR-3346)
2. Fixed Universal Analytics.
Fixed unit tests.
Added checks for site clones.
Added Dev Radiator to ignore for jest.

MAR-3346. Fixed Universal Analytics.

---

client/components/Ebook/ReadForm.vue
client/components/core/modals/ModalContentLocker.vue
client/components/core/modals/ModalEbook.vue
client/components/shared/UIFormCheckbox.vue
client/components/slices/EbookForm.vue
client/mixins/createLeadMixin.js
server/services/LeadsService.js
tests/unit/components/Ebook/__snapshots__/ReadForm.spec.js.snap
tests/unit/components/core/modals/__snapshots__/ModalEbook.spec.js.snap
tests/unit/components/shared/UIFormCheckbox.spec.js
tests/unit/components/shared/__snapshots__/UIFormCheckbox.spec.js.snap
tests/unit/components/slices/__snapshots__/EbookForm.spec.js.snap

the task: https://maddevs.atlassian.net/browse/MAR-3341
1. Created a new component UIFormCheckbox
2. Added a new custom field to send the form on the server side
3. Added  a new field in the sendpulse
4. Added test
5. Used the UIFormCheckbox component in 3 forms

MAR-3341. Created a UIFormCheckbox component

---

.github/workflows/seo-analyzer.yml
package.json

> [MAR-3301](https://maddevs.atlassian.net/browse/MAR-3301)
- Enable seo analyzer GitHub actions. (For all branches except maser)
- Removed from pre-push

MAR-3301 Enable seo analyzer GitHub actions

---

server/config/json/mainRedirects.json
server/index.js
server/middlewares/redirectToCorrectAuthorUrl.js
server/middlewares/tests/redirectToCorrectAuthorUrl.test.js
utils/getRoutes.js

1. [Пофиксить редиректы со старых урлов авторов](https://maddevs.atlassian.net/browse/MAR-3365)
2. Fixed wrong redirects.
Fix tests.
Disable Dev Radiator for staging and dev.

MAR-3365. Fixed wrong redirects.

---

client/prismicSlices/pageParts/EbooksWithFilterSlice/index.vue
tests/unit/prismicSlices/pageParts/EbooksWithFilterSlice/EbooksWithFilterSlice.spec.js
tests/unit/prismicSlices/pageParts/EbooksWithFilterSlice/__snapshots__/EbooksWithFilterSlice.spec.js.snap

1. [На странице Ebooks скрыть  NavLinkSlice ](https://maddevs.atlassian.net/browse/MAR-3333)
2. Disable pagination for ebooks when ebooks < 6.

MAR-3333. Disable pagination for ebooks when ebooks < 6.

---

nuxt.config.js

1. [Пофиксить баг при генерации HTML страницы авторов](https://maddevs.atlassian.net/browse/MAR-3383)
2. Fixed generate routes.

MAR-3383. Fixed generate routes.

---

client/components/core/FooterV2/FooterStaticNavigations.vue
client/data/footerNavigation.js

1) https://maddevs.atlassian.net/browse/MAR-3357
2) Added PDF links to footer.
3)

MAR-3357. Added PDF links to footer.

---

client/analytics/Event.js
client/plugins/gtag.js
tests/unit/analytics/Event.spec.js
utils/getPlugins.js

1. [Проверить код аналитики и понять причину не соответствия трафика между GA4 и UA](https://maddevs.atlassian.net/browse/MAR-3346)
2. Added check for clones for analytics.

MAR-3346. Added check for clones for analytics.

---

client/components/Cases/BuildDevTeam.vue
client/components/DeliveryModels/CTABanner.vue
client/data/footerNavigation.js
tests/unit/components/Cases/__snapshots__/BuildDevTeam.spec.js.snap
tests/unit/components/DeliveryModels/__snapshots__/CTABanner.spec.js.snap

1. [Поменять на Case Studies и delivery-models Anatoliy на Tony](https://maddevs.atlassian.net/browse/MAR-3461)
2. Replace Anatoliy to Tony. Remove About us pdf in footer.

MAR-3461. Replace Anatoliy to Tony. Remove About us pdf in footer.

---

package-lock.json
package.json

1. [Поменять на Case Studies и delivery-models Anatoliy на Tony](https://maddevs.atlassian.net/browse/MAR-3461)
2. Fixed node version.

MAR-3461. Fixed node version.

---

client/middleware/redirectToHomePage.js
utils/getRoutes.js

1. [Удалить страничку About и настроить редиректы с нее](https://maddevs.atlassian.net/browse/MAR-3416)
2. Added redirect from /about/ to /.
Delete /about/ from sitemap.

MAR-3416. Added redirect from /about/ to /.

---

nuxt.config.js

1. [Добавить код Hubspot на сайт](https://maddevs.atlassian.net/browse/MAR-3487)
2. Added HubSpot script.

MAR-3487. Added HubSpot script.

---

client/prismicSlices/pageParts/TechAndToolsNewSlice/components/LittleCard.vue

1. [Централизовать название OpenZeppelin  в слайсе тех стека](https://maddevs.atlassian.net/browse/MAR-3477)
2. Set scale title if to large.
Create variable for max letters length.
Change font-size for title.

MAR-3477. Set scale title if to large.

---

client/components/Cases/CasesList.vue
client/components/Cases/CasesListItem.vue
client/components/Cases/TitleDesc.vue
client/prismicSlices/pageParts/VideoSlice/index.vue
tests/unit/components/Cases/__snapshots__/CasesListItem.spec.js.snap

1. [Адаптировать размер карточек Case Studies на странице Case Studies](https://maddevs.atlassian.net/browse/MAR-3468)
2. Redesign adaptive cases card list.
Updated snapshots.

MAR-3468. Redesign adaptive cases card list.

---

server/middlewares/redirectToCorrectAuthorUrl.js
server/middlewares/redirectToRuCareerPostUrl.js

1. [Исправить проблему со страницами авторов, ошибка приходит с sentry](https://maddevs.atlassian.net/browse/MAR-3387)
2. Fixed a server error that occurs when you redirect to author.

MAR-3387. Fixed a server error that occurs when you redirect to author.

---

client/components/Ebook/ReadForm.vue
client/components/slices/EbookForm.vue

the task: https://maddevs.atlassian.net/browse/MAR-3529
1. Fixed reset function error when a ebook form is submitted

MAR-3529. Fixed reset error when form is submitted

---

client/prismicSlices/pageParts/PostsSectionSlice/variations/EbookPostsSectionSlice.vue

the task: https://maddevs.atlassian.net/browse/MAR-3478
1. Replaced margin to padding

MAR-3478. Replaced margin to padding

---

client/components/shared/Crumbs.vue
tests/unit/components/shared/__snapshots__/Crumbs.spec.js.snap

the task: https://maddevs.atlassian.net/browse/MAR-3401
1. Add a conditional operator to check the length of bread crumbs array
2. Update snapshots

MAR-3401. Fixed bread crumbs

---

client/components/Ebook/EbooksCard.vue

https://maddevs.atlassian.net/browse/MAR-3538
MAR-3398. Fix ebook card preview width.

MAR-3398. Fix ebook card preview width.

---

client/components/Blog/header/CustomerUniversity.vue
client/components/DeliveryModels/shared/ModelCard.vue
tests/unit/analytics/Event.spec.js
tests/unit/components/Blog/header/Blog.spec.js
tests/unit/components/Blog/header/CustomerUniversity.spec.js
tests/unit/components/Blog/header/__snapshots__/CustomerUniversity.spec.js.snap
tests/unit/components/Careers/OpenPositions.spec.js
tests/unit/components/Cases/BuildDevTeam.spec.js
tests/unit/components/Cases/__snapshots__/BuildDevTeam.spec.js.snap
tests/unit/components/DeliveryModels/CTABanner.spec.js
tests/unit/components/DeliveryModels/Main.spec.js
tests/unit/components/DeliveryModels/__snapshots__/CTABanner.spec.js.snap
tests/unit/components/DeliveryModels/shared/ModelCard.spec.js
tests/unit/components/Ebook/ReadForm.spec.js
tests/unit/components/Ebook/__snapshots__/ReadForm.spec.js.snap
tests/unit/components/core/chat/ChatModal/DevelopmentBody/index.spec.js
tests/unit/pages/case-studies/index.spec.js
tests/unit/prismicSlices/pageParts/CTABannerSlice/components/CTAModal.spec.js
tests/unit/prismicSlices/pageParts/EbooksWithFilterSlice/EbooksWithFilterSlice.spec.js

1. [Написать юнит тесты на те компоненты, которые не протестированы или протестированы не полностью](https://maddevs.atlassian.net/browse/MAR-3542)
2. Fixed all warnings in console when run unit tests.
Completed tests for ReadForm and Development chat modal.

MAR-3542. Fixed all warnings in console when run unit tests.

---

client/prismicSlices/pageParts/WeCreateProjectsFor/variations/WeCreateProjectsForWithMap/WeCreateProjectsForWithMap.vue

1) https://maddevs.atlassian.net/browse/MAR-3398
2) Added fonts styles for mobile view
3)

MAR-3398. We created projects for slice fonts styles added 

---

client/prismicSlices/pageParts/CardGridSlice/variations/CardGrid.vue

1) https://maddevs.atlassian.net/browse/MAR-3470 
2) Changed adaptive styles.
3)

MAR-3470. Changed adaptive styles.

---

client/prismicSlices/pageParts/PressCenter/index.vue
tests/unit/prismicSlices/pageParts/PressCenter/__snapshots__/index.spec.js.snap
tests/unit/prismicSlices/pageParts/PressCenter/index.spec.js

1) https://maddevs.atlassian.net/browse/MAR-3467
2) Changed fonts styles
3)

MAR-3467. Changed fonts styles

---

client/prismicSlices/pageParts/WeCreateProjectsFor/variations/WeCreateProjectsForWithMap/WeCreateProjectsForWithMap.vue

1)  https://maddevs.atlassian.net/browse/MAR-3398
2) Fixed map width and separator margins
3)

MAR-3398. Fixed map width and separator margins

---

server/config/json/mainRedirects.json
server/middlewares/redirectToCorrectUrl.js
server/middlewares/tests/redirectToCorrectUrl.test.js

1. [Настройка редиректов](https://maddevs.atlassian.net/browse/MAR-3580)
2. Fixed redirect from blog.maddevs.io.
Fixed unit test.

MAR-3580. Fixed redirect from blog.maddevs.io.

---

server/utils/devRadiator/config.js
server/utils/devRadiator/devRadiator.js

1) https://maddevs.atlassian.net/browse/MAR-3495
2) 
Added metrics collection checks. 
Fixed desktop icon in the slack message.

MAR-3495. Added metrics collection checks. 

---

jest/utils/checkCoverage.js
server/services/LeadsService.js
server/services/tests/LeadsService.spec.js

1. [Передавать Traffic source при скачивании ибука](https://maddevs.atlassian.net/browse/MAR-3596)
2. Added traffic source for ebooks jira board.
Added unit tests for LeadsService.

MAR-3596. Added traffic source for ebooks jira board.

---

client/prismicSlices/pageParts/ProjectStartSlice/index.vue
client/prismicSlices/pageParts/QuickProjectStart/index.vue

the task: https://maddevs.atlassian.net/browse/MAR-3581
1. Deleted a black line in the safari browser

MAR-3581. Deleted a black line in the safari browser

---

client/data/projectsFor.js
client/prismicSlices/pageParts/WeCreateProjectsFor/index.vue
client/prismicSlices/pageParts/WeCreateProjectsFor/variations/WeCreateProjectsForWithMap/WeCreateProjectsForWithMap.vue

1) https://maddevs.atlassian.net/browse/MAR-3597
2) Remove default slice variation from slice. Centered industries texts
3)

MAR-3597. Projects for slice refactoring

---

client/components/Blog/Main/AllPostsSection.vue

1) https://maddevs.atlassian.net/browse/MAR-3549
2) Changed button styles
3)

MAR-3549-change-button-in-blog. Changed button styles

---

client/components/core/Footer/Footer.vue
client/components/core/forms/SubscribeForm.vue
tests/unit/components/core/Footer/Footer.spec.js
tests/unit/components/core/Footer/__snapshots__/Footer.spec.js.snap

1. [MAR-3609: Добавить кнопку subscribe в футере](https://maddevs.atlassian.net/browse/MAR-3609)
2. Added Subscribe form in Footer.
Fixed tests.

MAR-3609. Added Subscribe form in Footer.

---

client/components/core/HeaderV2/HeaderNavigation.vue
client/helpers/checkCurrentRoute.js
tests/unit/components/core/HeaderV2/HeaderNavigation.spec.js
tests/unit/components/core/HeaderV2/__snapshots__/HeaderNavigation.spec.js.snap

the task: https://maddevs.atlassian.net/browse/MAR-3061
1. Refactored the logic for styling current navigation names
2. Updated tests

MAR-3061. Refactored the logic for styling current navigation names

---

client/components/core/HeaderV2/HeaderNavigation.vue
client/components/shared/Crumbs.vue

the task: https://maddevs.atlassian.net/browse/MAR-3061
1. Changed replace method in bread crumbs logic
2. Fixed conditional operator in the logic of navigation links

MAR-3061. Some changes have been made to bread crumbs and logic nav links

---

nuxt.config.js

1. [Добавить слайс баннер subscribe в призмик](https://maddevs.atlassian.net/browse/MAR-3610)
2. Added env for sendpulse

MAR-3610. Added env for sendpulse.

---

client/components/Blog/Post/Post.vue
client/components/core/forms/SubscribeForm.vue

1. [MAR-3651: Передача правильного traffic source у форм в футере и слайсе](https://maddevs.atlassian.net/browse/MAR-3651)
2. Fixed traffic source for jira.

MAR-3651. Fixed traffic source for jira.

---

client/components/shared/Crumbs.vue

https://maddevs.atlassian.net/browse/MAR-3217
1. Refactored logic of bread crumbs
The breadcrumbArray is array that created inside the reduce method, therefore change this array does not count as mutating an array in a different scope

MAR-3217. Refactored logic of bread crumbs

---

client/components/core/HeaderV2/index.vue

1. [MAR-3571: Изменить цвет кнопки Contact me](https://maddevs.atlassian.net/browse/MAR-3571)
2. Changed color for Contact Me button.

MAR-3571. Changed color for Contact Me button.

---

client/locales/en.json

the task: https://maddevs.atlassian.net/browse/MAR-3661
1. Changed description text on the careers page

MAR-3661. Changed description text on the careers page

---

client/components/Blog/Post/ContentLocker.vue
client/components/Blog/Post/Post.vue
client/components/core/HeaderV2/index.vue
client/components/core/Modal.vue
client/components/core/modals/ModalContentLocker.vue
tests/unit/components/Blog/Post/ContentLocker.spec.js
tests/unit/components/Blog/Post/Post.spec.js
tests/unit/components/Blog/Post/__snapshots__/Post.spec.js.snap
tests/unit/components/DeliveryModels/__snapshots__/CTABanner.spec.js.snap
tests/unit/components/core/modals/ModalContentLocker.spec.js
tests/unit/components/core/modals/__snapshots__/ModalContentLocker.spec.js.snap
tests/unit/components/core/modals/__snapshots__/ModalEbook.spec.js.snap

1. [MAR-3574: Внутреннее продвижение Ибуков (модалки)](https://maddevs.atlassian.net/browse/MAR-3574)
2. Added random output of ebooks on pages of posts by tags.
Fix search button bg.

MAR-3574. Added random output of ebooks on pages of posts by tags.

---

client/components/core/HeaderV2/index.vue

1. [Изменить цвет кнопки Contact me](https://maddevs.atlassian.net/browse/MAR-3571)
2. Bug fix bg burger button

MAR-3571. Bug fix bg burger button.

---

client/components/Blog/Main/AllPostsSection.vue

1) https://maddevs.atlassian.net/browse/MAR-3549
2) Changes color from red to white

MAR-3549-change-button-in-blog. Changes color from red to white

---

client/assets/styles/_global.scss
client/components/slices/index.vue
client/prismicSlices/pageParts/ProgressSlice/index.vue
tests/unit/prismicSlices/pageParts/ProgressSlice/__snapshots__/index.spec.js.snap

1. [MAR-2921: Переписать TextSlice для Prismic вариацию title](https://maddevs.atlassian.net/browse/MAR-2921)
2. Fixed anchor links for text slice.

MAR-2921. Fixed anchor links for text slice.

---

client/prismicSlices/pageParts/ProgressSlice/index.vue

1. [MAR-2921: Переписать TextSlice для Prismic вариацию title](https://maddevs.atlassian.net/browse/MAR-2921)
2. Bug fix ProgressSlice.

MAR-2921. Bug fix ProgressSlice.

---

client/components/Careers/shared/PositionForm.vue
server/controllers/CareersController.js
tests/unit/components/Careers/shared/PositionForm.spec.js

the task: 
1. Remove the recaptcha from the position form
2. Remove the recaptcha checking the conditional operator on the back side
3. Update tests

MAR-3662. Remove recaptcha from the position form, update tests

---

client/components/core/modals/ModalContentLocker.vue

1. [MAR-3574: Внутреннее продвижение Ибуков (модалки)](https://maddevs.atlassian.net/browse/MAR-3574)
2. Fixed text for Approach Ebook.

MAR-3574. Fixed text for Approach Ebook.

---

client/analytics/events.js
client/components/Ebook/ReadForm.vue
client/components/core/forms/BaseForm.vue
client/components/core/forms/SubscribeForm.vue
client/components/slices/EbookForm.vue
tests/unit/components/Ebook/ReadForm.spec.js
tests/unit/components/core/forms/FooterForm.spec.js
tests/unit/components/core/forms/GetExpertAdviceForm.spec.js
tests/unit/components/core/forms/GetYourTrustedItPartnerForm.spec.js
tests/unit/components/core/forms/IndividualsForm.spec.js
tests/unit/components/core/forms/InfrastructureAuditForm.spec.js
tests/unit/components/core/forms/OrderProjectFromUsForm.spec.js
tests/unit/components/core/forms/SubscribeForm.spec.js
tests/unit/components/core/forms/TeamsForm.spec.js
tests/unit/components/core/modals/ModalGetExpertAdvice.spec.js
tests/unit/components/core/modals/ModalGetYourTrustedItPartner.spec.js
tests/unit/components/core/modals/ModalIndividuals.spec.js
tests/unit/components/core/modals/ModalInfrastructureAudit.spec.js
tests/unit/components/core/modals/ModalOrderProjectFromUs.spec.js
tests/unit/components/core/modals/ModalTeams.spec.js
tests/unit/components/slices/EbookForm.spec.js

1. [MAR-3600: Выводить количество подписок на рассылку](https://maddevs.atlassian.net/browse/MAR-3600)
2. Added GA4 events for subscribe form.

MAR-3600. Added GA4 events for subscribe form.

---

server/config/json/mainRedirects.json
tests/unit/prismicSlices/pageParts/QuickProjectStart/index.spec.js

1. [Багфикс редиректов на CU посты](https://maddevs.atlassian.net/browse/MAR-3670)
2. Fixed redirects.

MAR-3670. Fixed redirects.

---

client/data/footerNavigation.js
tests/unit/components/core/Footer/__snapshots__/FooterStaticNavigation.spec.js.snap

the task: https://maddevs.atlassian.net/browse/MAR-3575
1. Uploaded pdf files to the AWS s3
2. Updated data in the footer component

MAR-3575. Update promo materials in the footer component

---

client/data/footerNavigation.js
tests/unit/components/core/Footer/__snapshots__/FooterStaticNavigation.spec.js.snap

the task: https://maddevs.atlassian.net/browse/MAR-3575
1. Uploaded pdf files to the AWS s3
2. Updated data in the footer component

MAR-3575. Update data in the footer and update snapshots

---

client/components/core/Footer/FooterContacts.vue
tests/unit/components/core/Footer/__snapshots__/FooterContacts.spec.js.snap

Test deploy 1

---

client/components/core/Footer/Footer.vue
tests/unit/components/core/Footer/__snapshots__/Footer.spec.js.snap

Test deploy 2

---

client/components/core/Footer/FooterNavbar.vue
tests/unit/components/core/Footer/__snapshots__/FooterNavbar.spec.js.snap

Test deploy 3

---

client/app/router.scrollBehavior.js
client/prismicSlices/pageParts/ContactsSlice/variations/FirstVariation.vue

https://maddevs.atlassian.net/browse/MAR-3062
Added anchor link and parallax effect to contacts data

MAR-3683. Added anchor link and parallax effect to contacts data

---

client/prismicSlices/pageParts/ContactsSlice/variations/FirstVariation.vue

https://maddevs.atlassian.net/browse/MAR-3683
Fixed mobile view anchor link

MAR-3683. Fixed mobile view anchor link

---

client/prismicSlices/pageParts/ContactsSlice/variations/FirstVariation.vue

https://maddevs.atlassian.net/browse/MAR-3683
Changed parallax element offset to center

MAR-3683. Changed parallax element offset to center

---

client/components/core/Footer/Footer.vue
client/components/core/Footer/FooterContacts.vue
client/components/core/Footer/FooterNavbar.vue
tests/unit/components/core/Footer/__snapshots__/Footer.spec.js.snap
tests/unit/components/core/Footer/__snapshots__/FooterContacts.spec.js.snap
tests/unit/components/core/Footer/__snapshots__/FooterNavbar.spec.js.snap

Удалил тестовые данные которые использовал для проверки процесса деплоя на стейджинг.

MAR-3694. Removed testing data 

---

package-lock.json
package.json
server/radiator/index.js

the task: https://maddevs.atlassian.net/browse/MAR-3701
1. Updated version of the radiator package
2. Fixed the config file

MAR-3701. Update version of the radiator package, fix config

---

package-lock.json
package.json

MAR-3599. Updated radiator version

---

client/components/Cases/nambataxi/FaultTolerance.vue
tests/unit/components/Cases/bandpay/MeetTeam.spec.js
tests/unit/components/Cases/namba-taxi/FaultTolerance.spec.js
tests/unit/components/Cases/namba-taxi/__snapshots__/FaultTolerance.spec.js.snap
tests/unit/pages/careers/_uid.spec.js
tests/unit/pages/delivery-models/_uid.spec.js

1. [MAR-3542: Написать юнит тесты на те компоненты, которые не протестированы или протестированы не полностью](https://maddevs.atlassian.net/browse/MAR-3542)
2. Write tests.

MAR-3542. Write tests.

---

client/components/DeliveryModels/Banner.vue
tests/unit/components/DeliveryModels/__snapshots__/Banner.spec.js.snap

1. [MAR-3714: Мигание на станице Delivery models](https://maddevs.atlassian.net/browse/MAR-3714)
2. Fixed bug on start screen delivery models.

MAR-3714. Fixed bug on start screen delivery models.

---

utils/getRoutes.js

the task:
https://maddevs.atlassian.net/browse/MAR-2670
https://maddevs.atlassian.net/browse/MAR-3702
1. Added cutom-pages delivery models to the sitemap

MAR-3702. Added delivery-models pages to the sitemap

---

client/components/core/modals/ModalContentLocker.vue
package-lock.json
package.json

update the radiator version
fix color styles - using vars

fix: update the radiator version and replace hex color to vars

---

package-lock.json
package.json
server/index.js

1. Update the radiator version to 5.4.0

MAR-3472: update the radiator version

---

tests/unit/components/core/modals/ModalEbook.spec.js
tests/unit/components/core/modals/__snapshots__/ModalEbook.spec.js.snap

MAR-3708: update snapshots

---

package-lock.json
package.json

Update the radiator version to 5.5.0

MAR-3819-upd-radiator. Update the radiator version

---

package-lock.json
package.json

the task: https://maddevs.atlassian.net/browse/MAR-3819
1. Update the radiator version

update the radiator version

---

.github/workflows/seo-analyzer.yml
SEOAnalyzer/index.js
client/components/slices/index.vue
client/pages/_uid.vue
client/prismicSlices/pageParts/PressCenter/index.vue
package.json
utils/getRoutes.js

1. [MAR-3821: Починить падение СЕО Анализатора](https://maddevs.atlassian.net/browse/MAR-3821)
2. Fixed seo-analyzer.

MAR-3821. Fixed seo-analyzer.

---

client/components/slices/index.vue
tests/unit/components/slices/index.spec.js

1. [MAR-3606: Добавить возможность добавления атрибута nofollow для ссылок в призмике](https://maddevs.atlassian.net/browse/MAR-3606)
2. Added nofollow rel attribute.

MAR-3606. Added nofollow rel attribute.

---

package-lock.json
package.json

the task: https://maddevs.atlassian.net/browse/MAR-3472
1. Update the radiator version

MAR-3472. Update the radiator version
