client/assets/styles/cases/godee/_styles.scss, client/pages/case-studies/godee.vue
В Safari не работал parallax эффект,  потому что он реализован через css 3d трансформацию и у секции был установлен `overflow: hidden; `. <br />
`overflow: hidden` переопределяет свойства 3d трансформации в Safari и она перестаёт работать ( parallax эффекта нет ). <br />
Можно вот тут почитать:
- [Don't set overflow: hidden on elements with 3D transformed children](https://codepen.io/thebabydino/details/rACbl)
- https://htmlacademy.ru/blog/boost/tutorial/pure-css-parallax-websites
<br />
<br />
**Решение:** <br />
Я разрулил эту проблему с помощью настройки расположения слоёв друг над другом. <br />
Все секции с контентом завернул в див с `background: #fff` и обычным `z-index: 1` <br />
А секции с паралаксом дал `z-index: -9`, чтобы она проходила под дивами с контентом
=> MR-2022 Fixed section with parallax effect for GoDee case

client/pages/customer-university/_uid.vue
При рефакториге в рамках этой мрки https://github.com/maddevsio/maddevs/pull/713 затерли `getClusterData` метод, который доставал список всех CU постов. Этот список юзается:
- В дропдауне,  который в начале CU статьи
- Для навигационных кнопок next & prev post
- Для списка CU постов в конце статьи 
Вернул недостающие данные для поста
=> MR-2595 Fixed the CU posts page, added the cluter data with postsList

client/components/Blog/PostView.vue, client/components/Blog/slices/TextSlice.vue
Задача - https://maddevs.atlassian.net/browse/MAR-146
**В чём была проблема:**
Некоторые слова в тексте поста были очень длинными и выходили за пределы страницы в бок. Поэтому появлялся горизонтальный скролл.
**Решение:**
Добавил свойство `word-break: break-word` для контенера, который содержит весь контент поста
=> MAR-146 Fixed problem with horizontal scroll in the post page

client/app/router.scrollBehavior.js
1) Якорные ссылки не работали. Поменял scrollBehavior конфигурацию
Решения брал из этих статей:
- https://levelup.gitconnected.com/nuxt-js-custom-scrollbehavior-fired-after-page-loaded-cd94fd6ddd12
- https://zachcardoza.com/post/nuxtjs-smooth-scrolling-with-hash-links/
=> MAR-245 Fixed the scrollBehavior configuration for hash links

client/components/Blog/Main/CustomerUniversitySection.vue, client/components/Blog/shared/FeaturedPost.vue, client/components/Blog/shared/RecommendedBlogWidget.vue, client/helpers/formatDate.js, client/pages/blog/_uid.vue, client/pages/customer-university/_uid.vue
* В Sentry появились ошибки, связанные с использованием Intl на старом браузере(Firefox 45). Проверил через Browserstack, все корректно работает. 
* У нас подключается полифилл для старых браузеров, который решает проблему доступности. 
* На случай проблем и отсутствия Intl я добавил проверку на наличие Intl, а заодно еще и вытащил форматирование даты в отдельный хэлпер. Если в будущем будут проблемы с Intl, то нужно будет поправить только 1 хэлпер.
* Рассмотрел вариант добавления moment.js в проект, но отказался от него в связи с огромным весом библиотеки.
=> MAR-725. Fixed sentry issue with Intl.

client/components/Blog/Main/AllPostsSection.vue, client/components/Blog/Main/Main.vue, client/components/Blog/shared/PostAuthor.vue, client/components/Blog/shared/RecommendedBlogWidget.vue
1. Добавил новые watch в компонент AllPostsSection.vue, он отрабатывает как только изменится значение postsCategory переменной, это позволяет добавить lazy для новые постов которые появились после фильтрации
2. Добавил новые watch в компонент Main.vue, он отвечает за навешивание lazy loading для асинхронно подгружаемых блог постов, рядом используемый миксин не может хендлить асинхронные посты и поэтому пришлось добавить этот фикс
3. Добавил фикс который решает проблему с обновлением картинок у фильтрованных постов. Фикс работает следующим образом. Вотчер смотрит на пропсы компонента, если те изменили, то он выставляет актуальный класс для картинки и скрипт который добавляет lazy loading отрабатывает корректно
P.s сами фиксы получились костыльными, но чтобы реализовать логику лучше, нужно …
=> MAR-153 fix problem with lazy for recommended posts

client/components/Cases/godee/cards/CardGoDeeFeature.vue, tests/components/Cases/godee/__snapshots__/DevelopmentGoals.spec.js.snap, tests/components/Cases/godee/__snapshots__/Main.spec.js.snap, tests/components/Cases/godee/__snapshots__/Mvp.spec.js.snap
Исправил баг с анимацией карточек в кейсе GoDee
Причина бага:
Проблема была с lazy loading логикой, на момент загрузки страницы y иконок не выставлялась дефолтная высота и ширина, из-за этого все расчеты высоты секции с карточками в скриптах были не правильными, я поправил эту проблему и анимация заработала одинаково во всех браузерах.
=> MAR-752 fix animation bug in GoDee case

client/components/Cases/nambafood/cards/CardUseCase.vue
Поправил ототражение картинок в карточках из секции "Typical usage scenarios and user roles" в Namba Food кейсе. Картинки не отображались в Safari браузере
=> MAR-814 Fixed display of pictures for scenarios cards in the Namba Food case ( bug in Safari browser )

client/components/Blog/header/Common.vue, client/components/Blog/header/CustomerUniversity.vue, tests/components/Blog/header/__snapshots__/Blog.spec.js.snap, tests/components/Blog/header/__snapshots__/Common.spec.js.snap, tests/components/Blog/header/__snapshots__/CustomerUniversity.spec.js.snap
Задача - https://maddevs.atlassian.net/browse/MAR-806
**Проблема:**
Заглавная картинка блога была мыльной.
**Решение:**
- Поправил стили для отображения заглавной картинки
- Для retina дисплеев нужна картинка с x2 размером, т.е 983px x 2 = 1966px по ширине минимум. У нас картинки с размерами 2000px по ширине.  Поэтому оригинальный размер как раз подходит. Добавил `srcset` аттрибут для retina дисплеев, в котором выводится картинка в полном размере без кропа
=> MAR-806 Corrected sizes of introduction image in the PostView page, added lazy loading for this image

client/mixins/buildPostPageMixin.js
*  Исправил недочет из-за которого показатели Health score упали на 42%. Был добавлен конечный слеш для всех ссылок на статьи в блоге. Видимо при переносе забыли добавить конечный слеш, так как это не самый очевидный кейс в коде. 
* Чтобы в дальнейшем такого не повторилось, я поговорил с Денисом и предложил ему добавить в тесты для SEO проверку на наличие конечного слеша у URL.
=> MAR-846 added trailing slash for blog pages url

client/components/Cases/sjmc/HardwareVideo.vue, client/components/core/forms/FooterForm.vue, tests/__snapshots__/caseSJMC.spec.js.snap, tests/components/Cases/sjmc/__snapshots__/Hardware.spec.js.snap, tests/components/Cases/sjmc/__snapshots__/HardwareVideo.spec.js.snap
1. Исправил верстку секции с телефоном в кейсу музея, удалил жестко заданную высоту у видео через атрибут так как этот параметр ломал всю верстку 
2. Поправил цвет плейсхолдеров в футере убрав у них прозрачность которую по дефолту добавляет Firefox браузер
=> MAR-874 fix minor bugs in markup

client/store/modules/blogAuthors.js, tests/store/blogAuthors.spec.js
Задача в рамках которой работал: https://maddevs.atlassian.net/browse/MAR-877
1. Добавил условие при котором мутация будет вызываться только в случае если api метод вернет массив и его можно будет перебрать методом map() в мутации. 
2. Модифицировал один из существующих тестов для action функции и добавил один новый который проверяет что будет если api метод вернет не массив а что-то другое
Предположительную причину проблемы описал в задаче которую приложил выше.
=> MAR-955 update logic for vuex action getBlogAuthors

client/components/Cases/sjmc/Hardware.vue, client/components/Cases/sjmc/HardwareVideo.vue
Задача - https://maddevs.atlassian.net/browse/MAR-734
Сейчас на странице кейса музея на iOS устройствах вместо видео с телефоном - просто статичная картинка. По задумке там должен был быть видос который запускается по клику. От видео на время пришлось отказаться так как оно отображалось не правильно, точнее оно вообще не отображался ровно до того момента пока на него не кликнешь. 
В рамках этой задачи нужно исправить баг с отображением и выпилить статичную картинку.
** Изменения:**
- Выпилил картинку
- Поправил стили для видео тега
=> MAR-734 Fixed display of video with iPhone in SJMC case

nuxt.config.js
Добавил настройку игнорирования компонента veeqo.vue при сборке проекта, чтобы страница не попала на прод. 
Сделал согласно вот этой документации: https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-ignore#the-ignore-property
Добавил игнорирование в nuxt.config для того чтобы все настройки в проекте были в одном файле
=> Added ignore config for veeqo case page

client/components/Blog/shared/PostAuthor.vue, client/components/slices/AuthorSlice.vue, client/components/slices/EmbedSlice.vue, client/components/slices/ImageAttributesSlice.vue, tests/components/slices/__snapshots__/AuthorSlice.spec.js.snap, tests/components/slices/__snapshots__/ImageAttributesSlice.spec.js.snap, tests/components/slices/__snapshots__/index.spec.js.snap
1. Отпимизировал картинки на странице блог постов, чтобы на них не орал PSI(https://developers.google.com/speed/pagespeed/insights/?hl=ru)
2. Выставил дефолтную высоту и ширину картинкам
3. Подключил картинку в Embed блоке через img тег и добавил свойство lazy loading
=> MAR-1059 optimize images in blog post pages

client/components/slices/EmbedSlice.vue
Changed styles for image in Embeded slice
BEFORE: 
AFTER:
=> MAR-1683 changed styles for image in Embeded slice

client/components/Blog/Post/ContentLocker.vue, client/store/modules/blog.js, jest/configs/coverageThreshold.config.js, tests/api/ipInfo.spec.js, tests/components/Blog/Post/ContentLocker.spec.js, tests/store/blog.spec.js, tests/store/blogTags.spec.js
Link to task: [MAR-1859](https://maddevs.atlassian.net/browse/MAR-1859)
1. Added a function to interact with Vuex
2. The default is stored in Vuex
3. Now the content locker appears once per session, until the first full page reload
=> MAR-1859. Changed number of views of the content locker per session

client/components/core/modals/ModalSearch.vue, client/pages/blog/search-result/index.vue, tests/components/core/modals/ModalSearch.spec.js, tests/components/core/modals/__snapshots__/ModalSearch.spec.js.snap
1. Refactored `listenKeys` function 
2. Added new tests for `ModalSearch` component
3. Remove unuse `resetLazyLoad` method, fix this bug: https://maddevs.atlassian.net/browse/MAR-1944
4. Task: https://maddevs.atlassian.net/browse/MAR-1659
=> MAR-1659 added new tests for ModalSearch component

client/components/Cases/sjmc/SJMCVideo.vue
1) https://maddevs.atlassian.net/browse/MAR-2015
2) Fixed error "Cannot read properties of undefined (reading 'removeEventListener')"
=> MAR-2015.  Fixed error "Cannot read properties of undefined (reading 'removeEventListener')"

client/components/core/HeaderV2/HeaderMobile/HeaderMobileMenu.vue, client/components/core/HeaderV2/HeaderMobile/HeaderMobileSection.vue
Task: https://maddevs.atlassian.net/browse/MAR-2087
A quick touch up of HeaderMobileMenu.vue and HeaderMobileSection.vue to eliminate "Others" subsection in non-nested sections
=> MAR-2087 Removed subsection Others in Clients и Insights sections 

client/components/DeliveryModels/Banner.vue, client/components/core/Privacy.vue, client/prismicSlices/pageParts/StartScreen/index.vue, tests/unit/components/DeliveryModels/__snapshots__/Banner.spec.js.snap
**Task**: https://maddevs.atlassian.net/browse/MAR-2086
**Done**: 
increased spacing and decreased font-size to 100 in StartScreen slice. 
Adjusted Delivery Models Section to look identical to the StartScreen slice.
Changed font-family to Inter in privacy section
=> Mar-2086 minor fixes in new sections

client/components/Ebook/Read.vue, tests/unit/components/Ebook/__snapshots__/Read.spec.js.snap
Link to the task: https://maddevs.atlassian.net/browse/MAR-2203
1. Deleted padding from ebook-read and added padding to &__titile
2. The anchor link was postponed from ebook-read to h2 tag
3. Updated styles
=> MAR-2203. Deleted padding from .ebook-read & added padding to .&__title

client/prismicSlices/pageParts/TeamCards/index.vue
the task: https://maddevs.atlassian.net/browse/MAR-2443
1. Added vertical-align: middle; style to the img element for centralizing the image in the wrapper
=> MAR-2443. Fixed styles in the TeamCards component & updated snapshots

client/prismicSlices/pageParts/CtaBannerSlice/index.vue
The task: https://maddevs.atlassian.net/browse/MAR-2643
1. Deleted breakpoint 900px from the CtaBannerSlice for correctly render
=> MAR-2643. Deleted breakpoint 900px in the CtaBannerSlice.vue

client/prismicSlices/pageParts/GridLottieSlice/variations/GridLottieLink.vue
the task: https://maddevs.atlassian.net/browse/MAR-2652
1. Changed font sizes in the CardLottieLing component
=> MAR-2652. Changed font sizes in the CardLottieLing component

nuxt.config.js, server/middlewares/redirectToValidLink.js, server/middlewares/tests/redirectToValidLink.spec.js
> [MAR-2712](https://maddevs.atlassian.net/browse/MAR-2712)
- Enabled trailingSlash.
- New logic for redirectToValidLinks middleware.
- Updated test.
=> MAR-2712. Fix dublicated pages

client/components/shared/Crumbs.vue
the subtask: https://maddevs.atlassian.net/browse/MAR-3040
1. Fixed colors in the Crumbs component
=> MAR-3040. Fixed color styles in the component

client/components/core/HeaderV2/index.vue, client/components/shared/Crumbs.vue, tests/unit/components/shared/Crumbs.spec.js, tests/unit/components/shared/__snapshots__/Crumbs.spec.js.snap
the subtask: https://maddevs.atlassian.net/browse/MAR-3042
1. Fixed color styles
2. Fixed functional to get the route and titles for breadcrumbs
3. Updated tests and snapshots
=> MAR-3042. Refactored breadcrumbs

client/prismicSlices/pageParts/GridLottieSlice/variations/GridLottieLink.vue, client/prismicSlices/pageParts/GridLottieSlice/variations/GridWithAnimationOptionSlice.vue
1. [Адаптировать шрифты на слайсе GridLottieSlice](https://maddevs.atlassian.net/browse/MAR-3466)
2. Redesigned mobile adaptive for CardGridLottieSlice.
Fixed styles for arrow button.
Replaced /deep/ to ::v-deep.
=> MAR-3466. Redesigned mobile adaptive for CardGridLottieSlice.

client/components/Ebook/EbooksCard.vue, client/store/modules/ebooks.js
1. [MAR-3555: Показывать весь текс в названиях книжек](https://maddevs.atlassian.net/browse/MAR-3555)
2. Removed three dots from ebook cards.
=> MAR-3555. Removed three dots from ebook cards.
